Repository NASA-AMMOS/aerie-ui, pull requests merged in 2022-12, with the labels that each got.

#286 Move stores out of Timeline component
  src/components/timeline/ConstraintViolations.svelte
  src/components/timeline/LayerActivity.svelte
  src/components/timeline/LayerLine.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelineCursors.svelte
  src/components/timeline/TimelineHistogram.svelte
  src/components/timeline/TimelineLockControl.svelte
  src/components/timeline/TimelinePanel.svelte
  src/components/timeline/TimelineViewControls.svelte
  src/components/timeline/XAxis.svelte
  src/stores/activities.ts
  src/types/activity.d.ts
Labels: refactor

#268 Include details of page route in title
  e2e-tests/tests/plan-merge.test.ts
  src/components/app/PageTitle.svelte
  src/components/constraints/ConstraintForm.svelte
  src/components/expansion/ExpansionRuleForm.svelte
  src/components/scheduling/SchedulingGoalForm.svelte
  src/components/sequencing/SequenceForm.svelte
  src/routes/+error.svelte
  src/routes/constraints/+page.svelte
  src/routes/dictionaries/+page.svelte
  src/routes/expansion/rules/+page.svelte
  src/routes/models/+page.svelte
  src/routes/plans/+page.svelte
  src/routes/plans/[id]/+page.svelte
  src/routes/scheduling/goals/+page.svelte
  src/routes/scheduling/goals/edit/[id]/+page.svelte
  src/routes/scheduling/goals/new/+page.svelte
  src/routes/sequencing/+page.svelte
Labels: feature

#303 Simplify test setup
  .github/workflows/test.yml
  docker-compose-test.yml
Labels: ci

#285 Timeline row view editing
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan.test.ts
  e2e-tests/tests/timeline-view-editing.test.ts
  src/components/form/ColorPicker.svelte
  src/components/menus/GridMenu.svelte
  src/components/timeline/LayerLine.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/RowHorizontalGuides.svelte
  src/components/timeline/TimelineCursor.svelte
  src/components/timeline/TimelineCursors.svelte
  src/components/timeline/form/TimelineDetailsPanel.svelte
  src/components/timeline/form/TimelineEditorPanel.svelte
  src/css/app.css
  src/routes/plans/[id]/+page.svelte
  src/stores/views.ts
  src/utilities/timeline.test.ts
  src/utilities/timeline.ts
Labels: feature

#305 Update to latest svelte-tags-input version
  package-lock.json
  package.json
  src/components/ui/Tags.svelte
  src/components/ui/Tags.svelte.test.ts
Labels: build

#310 Account for leap year when validating timestamps
  src/utilities/time.test.ts
  src/utilities/time.ts
  src/utilities/validators.test.ts
  src/utilities/validators.ts
Labels: fix

#312 Forward events to recursive calls of the SplitGrid component
  src/components/ui/SplitGrid.svelte
Labels: fix

#317 Add UI view schema and validate endpoint
  package-lock.json
  package.json
  src/routes/view/validate/+server.ts
  src/schemas/ui-view-schema.json
Labels: refactor

#318 Generate default UI view
  e2e-tests/tests/plan.test.ts
  e2e-tests/tests/timeline-view-editing.test.ts
  src/components/timeline/Timeline.svelte
  src/components/view/ViewsPanel.svelte
  src/routes/plans/[id]/+page.svelte
  src/routes/plans/[id]/+page.ts
  src/stores/views.ts
  src/types/timeline.d.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/view.ts
Labels: feature, breaking change

#314 Add table resize options to context menus
  src/components/activity/ActivityTablePanel.svelte
  src/components/expansion/ExpansionSetForm.svelte
  src/components/ui/DataGrid/BulkActionDataGrid.svelte
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
  src/components/ui/DataGrid/column-menu/ColumnResizeContextMenu.svelte
Labels: feature

#313 Show plan association for scheduling goals/conditions
  src/components/scheduling/conditions/SchedulingConditionForm.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/routes/scheduling/conditions/edit/[id]/+page.svelte
  src/routes/scheduling/conditions/edit/[id]/+page.ts
  src/routes/scheduling/conditions/new/+page.svelte
  src/routes/scheduling/conditions/new/+page.ts
  src/routes/scheduling/goals/edit/[id]/+page.svelte
  src/routes/scheduling/goals/edit/[id]/+page.ts
  src/routes/scheduling/goals/new/+page.svelte
  src/routes/scheduling/goals/new/+page.ts
  src/types/plan.d.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: feature

#320 Generate resource rows for default view
  e2e-tests/tests/plan.test.ts
  e2e-tests/tests/timeline-view-editing.test.ts
  src/routes/plans/[id]/+page.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/view.ts
Labels: feature
