Repository NASA-AMMOS/aerie-ui, pull requests merged in 2022-11, with the labels that each got.

#209 feat: track editor metadata dirty states
  src/components/constraints/ConstraintForm.svelte
  src/components/expansion/ExpansionRuleForm.svelte
  src/components/scheduling/SchedulingGoalForm.svelte
  src/components/sequencing/SequenceForm.svelte
Labels: feature

#214 build: upgrade deps to latest
  package-lock.json
  package.json
Labels: build

#212 refactor: Rename condition -> constraint
  src/utilities/gql.ts
Labels: refactor

#201 feat: merge review page
  src/components/activity/ActivityForm.svelte
  src/components/activity/ActivityFormPanel.svelte
  src/components/app/Nav.svelte
  src/components/app/NavButton.svelte
  src/components/form/Input.svelte
  src/components/menus/Menu.svelte
  src/components/menus/MenuItem.svelte
  src/components/menus/PlanMenu.svelte
  src/components/modals/ConfirmModal.svelte
  src/components/modals/CreatePlanBranchModal.svelte
  src/components/modals/Modal.svelte
  src/components/modals/ModalFooter.svelte
  src/components/modals/PlanBranchesModal.svelte
  src/components/modals/PlanMergeRequestsModal.svelte
  src/components/parameters/ParameterRecSeries.svelte
  src/components/parameters/Parameters.svelte
  src/components/plan/PlanMergeRequestStatusBadge.svelte
  src/components/plan/PlanMergeRequestsStatusButton.svelte
  src/components/plan/PlanMergeReview.svelte
  src/components/plan/PlanMergeReviewUserInfo.svelte
  src/components/ui/CssGridGutter.svelte
  src/components/ui/Highlight.svelte
  src/components/ui/Panel.svelte
  src/components/ui/UserBadge.svelte
  src/css/app.css
  src/css/stellar.css
  src/routes/constraints/+layout.svelte
  src/routes/dictionaries/+page.svelte
  src/routes/expansion/+layout.svelte
  src/routes/models/+page.svelte
  src/routes/plans/+page.svelte
  src/routes/plans/[id]/+page.svelte
  src/routes/plans/[id]/+page.ts
  src/routes/plans/[id]/merge/+page.svelte
  src/routes/plans/[id]/merge/+page.ts
  src/routes/scheduling/+layout.svelte
  src/routes/sequencing/+layout.svelte
  src/stores/plan.ts
  src/types/activity.d.ts
  src/types/plan.d.ts
  src/utilities/activities.ts
  src/utilities/effects.ts
  src/utilities/generic.ts
  src/utilities/gql.ts
  src/utilities/modal.ts
Labels: feature

#215 docs: update developer.md
  docs/DEVELOPER.md
Labels: documentation

#216 fix: span arguments
  src/utilities/activities.ts
Labels: fix

#217 feat: truncate long y axis labels with middle ellipses
  src/components/timeline/RowYAxes.svelte
Labels: feature

#224 test: init plan merge e2e
  e2e-tests/tests/plan-merge.test.ts
  src/components/activity/ActivityTypesPanel.svelte
  src/components/plan/PlanMergeRequestsStatusButton.svelte
Labels: test

#233 fix: request count computation for merge request modal
  src/components/modals/PlanMergeRequestsModal.svelte
Labels: fix

#237 fix: merge review icon update
  src/components/plan/PlanMergeReview.svelte
Labels: fix

#228 feat: prevent users from editing locked plan
  src/components/modals/ModalHeader.svelte
  src/components/modals/PlanLockedModal.svelte
  src/routes/plans/[id]/+page.svelte
  src/stores/plan.ts
  src/utilities/gql.ts
  src/utilities/modal.ts
Labels: feature

#245 fix: satisfied activities list
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/scheduling.test.ts
  src/components/scheduling/SchedulingGoal.svelte
  src/components/scheduling/SchedulingGoalAnalysesActivities.svelte
  src/components/timeline/LayerActivity.svelte
  src/utilities/activities.ts
Labels: fix

#241 fix: Sort merge requests
  src/utilities/gql.ts
Labels: fix

#244 feat: Alert user on Merge Review page if the review has ended
  src/components/modals/MergeReviewEndedModal.svelte
  src/components/plan/PlanMergeReview.svelte
  src/components/timeline/RowYAxes.svelte
  src/utilities/gql.ts
  src/utilities/modal.ts
Labels: feature

#259 release: version 1.0.0
  package-lock.json
  package.json
Labels: release

#263 Properly reset highlighted activity keys in merge review
  src/components/activity/ActivityForm.svelte
Labels: fix

#258 Add draggable handle to console to resize the height
  src/components/console/Console.svelte
  src/components/console/ConsoleDragHandle.svelte
Labels: feature

#271 Handle case for undefined columnStates in table menu
  src/components/activity/ActivityTableMenu.svelte
Labels: fix

#273 Upgrade deps to latest
  package-lock.json
  package.json
Labels: build

#274 Add errors caught from requests to console
  src/components/console/ConsoleSection.svelte
  src/stores/errors.ts
  src/types/errors.d.ts
  src/utilities/effects.ts
  src/utilities/errors.ts
Labels: feature

#278 Subscribe to activity types
  src/components/activity/ActivityForm.svelte
  src/components/activity/ActivityFormPanel.svelte
  src/components/activity/ActivityTable.svelte
  src/components/activity/ActivityTablePanel.svelte
  src/components/activity/ActivityTypesPanel.svelte
  src/components/expansion/ExpansionRuleForm.svelte
  src/components/expansion/ExpansionSetForm.svelte
  src/components/plan/PlanMergeReview.svelte
  src/components/simulation/SimulationPanel.svelte
  src/routes/plans/[id]/+page.svelte
  src/routes/plans/[id]/+page.ts
  src/stores/expansion.ts
  src/stores/plan.ts
  src/stores/simulation.ts
  src/types/activity.d.ts
  src/types/model.d.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: refactor

#282 Refactor to make components more functional
  src/components/activity/ActivityDecomposition.svelte
  src/components/activity/ActivityDecomposition.svelte.test.ts
  src/components/activity/ActivityForm.svelte
  src/components/activity/ActivityFormPanel.svelte
  src/components/activity/ActivityTable.svelte
  src/components/activity/ActivityTablePanel.svelte
  src/components/parameters/ParameterRecStruct.svelte
  src/components/ui/DataGrid/BulkActionDataGrid.svelte
Labels: refactor

#264 Timeline view editing
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan.test.ts
  src/components/form/DatePickerField.svelte
  src/components/form/Input.svelte
  src/components/menus/GridMenu.svelte
  src/components/timeline/TimelineCursors.svelte
  src/components/timeline/form/TimelineDetailsPanel.svelte
  src/routes/plans/[id]/+page.svelte
  src/utilities/timeline.ts
Labels: feature
