Repository NASA-AMMOS/aerie-ui, pull requests merged in 2023-03, with the labels that each got.

#418 Add view download button to ViewsTable
  src/components/ui/DataGrid/DataGridActions.svelte
  src/components/view/ViewsTable.svelte
Labels: feature

#423 Pass update through view toggle
  src/components/timeline/Row.svelte
  src/stores/views.ts
  src/types/view.ts
  src/utilities/view.ts
Labels: fix

#424 Change the "reset view" copy depending on if viewing a saved view
  src/components/menus/ViewMenu.svelte
Labels: refactor

#431 Bump stellar version
  package-lock.json
  package.json
Labels: refactor

#432 Release v1.2.0
  package-lock.json
  package.json
Labels: release

#437 Upgrade deps to latest
  package-lock.json
  package.json
  src/components/plan/PlanMergeReview.test.ts
  src/components/scheduling/goals/SchedulingGoalForm.svelte.test.ts
  vite.config.js
Labels: build

#439 Remove deep GQL query for Seq JSON
  src/utilities/gql.ts
Labels: refactor, sequencing

#444 Update stellar theme for ag-grid to use correct font source
  src/css/ag-grid-stellar.css
Labels: fix

#445 Use SequenceSeqJson query type
  src/utilities/gql.ts
Labels: fix

#448 ActionDataGrid deleteItem event fix
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
Labels: fix

#447 Include external resources in resource layer filter options and sort options
  src/components/timeline/form/TimelineEditorPanel.svelte
Labels: fix

#446 Show both data and trace in error console if both are present
  src/components/console/ConsoleSection.svelte
Labels: feature

#449 Mark Simulation as Dirty when Simulation Revision Changes
  src/components/simulation/SimulationPanel.svelte
  src/stores/simulation.ts
  src/types/simulation.ts
  src/utilities/gql.ts
Labels: bug, fix

#451 Release v1.3.0
  package-lock.json
  package.json
Labels: release

#406 Refactor to remove Activity type
  e2e-tests/data/invalid-view.json
  e2e-tests/data/valid-view.json
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan-merge.test.ts
  e2e-tests/tests/plan.test.ts
  e2e-tests/tests/timeline-view-editing.test.ts
  src/components/activity/ActivityAnchorForm.svelte
  src/components/activity/ActivityAnchorForm.svelte.test.ts
  src/components/activity/ActivityDecomposition.svelte
  src/components/activity/ActivityDecomposition.svelte.test.ts
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/activity/ActivityDirectiveSourceForm.svelte
  src/components/activity/ActivityDirectivesTable.svelte
  src/components/activity/ActivityDirectivesTablePanel.svelte
  src/components/activity/ActivityForm.svelte
  src/components/activity/ActivityFormPanel.svelte
  src/components/activity/ActivitySpanForm.svelte
  src/components/activity/ActivitySpansTable.svelte
  src/components/activity/ActivitySpansTablePanel.svelte
  src/components/activity/ActivityTableMenu.svelte
  src/components/expansion/ExpansionSetForm.svelte
  src/components/menus/GridMenu.svelte
  src/components/parameters/Parameters.svelte
  src/components/plan/PlanMergeReview.svelte
  src/components/scheduling/goals/SchedulingGoalAnalysesActivities.svelte
  src/components/simulation/SimulationPanel.svelte
  src/components/timeline/ConstraintViolations.svelte
  src/components/timeline/LayerActivity.svelte
  src/components/timeline/LayerLine.svelte
  src/components/timeline/LayerXRange.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelineHistogram.svelte
  src/components/timeline/TimelinePanel.svelte
  src/components/timeline/Tooltip.svelte
  src/components/ui/DataGrid/BulkActionDataGrid.svelte
  src/components/ui/DataGrid/DataGrid.svelte
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
  src/components/ui/PlanGrid.svelte
  src/routes/plans/[id]/+page.svelte
  src/schemas/ui-view-schema.json
  src/stores/activities.ts
  src/stores/simulation.ts
  src/stores/views.ts
  src/types/activity.ts
  src/types/constraint.ts
  src/types/simulation.ts
  src/types/timeline.ts
  src/types/view.ts
  src/utilities/activities.test.ts
  src/utilities/activities.ts
  src/utilities/effects.ts
  src/utilities/generic.ts
  src/utilities/gql.ts
  src/utilities/resources.ts
  src/utilities/time.ts
  src/utilities/view.ts
Labels: breaking change, refactor

#508 Set Sim Bounds to Plan Bounds on Plan Creation
  src/types/simulation.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: fix, simulation

#510 Explicitly check anchor_id against `null`
  src/components/activity/ActivityAnchorForm.svelte
  src/components/activity/ActivityDirectiveForm.svelte
Labels: fix

#436 Activity layer rendering
  package-lock.json
  package.json
  src/assets/span-hash-marks.svg
  src/components/form/ColorPicker.svelte
  src/components/form/ColorPresetsPicker.svelte
  src/components/timeline/LayerActivity.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelinePanel.svelte
  src/components/timeline/form/TimelineEditorPanel.svelte
  src/components/ui/DataGrid/DataGrid.svelte
  src/stores/activities.ts
  src/types/timeline.ts
  src/utilities/color.ts
  src/utilities/effects.ts
  src/utilities/timeline.ts
  src/utilities/view.ts
Labels: feature

#513 Remove logic in table that's setting selected row to null
  src/components/ui/DataGrid/DataGrid.svelte
Labels: fix

#456 Lock/Unlock Changes to Activity Directives
  src/components/activity/ActivityFormPanel.svelte
  src/stores/plan.ts
Labels: feature

#523 Pass 'disabled' prop to activity preset input
  src/components/activity/ActivityDirectiveForm.svelte
Labels: fix

#522 Basic simulation time inputs
  src/components/form/DatePickerField.svelte
  src/components/simulation/SimulationPanel.svelte
  src/components/ui/DatePicker/DatePicker.svelte
  src/components/ui/DatePicker/DatePickerActionButton.svelte
Labels: feature, simulation

#526 Fix sim panel default args
  src/components/simulation/SimulationPanel.svelte
Labels: bug, fix

#530 Firefox activity selection fix
  src/utilities/activities.ts
Labels: fix

#532 Ensure input exists before attempting to modify properties
  src/components/ui/Tags.svelte
Labels: bug, fix

#531 Fix sim time for spans
  src/components/timeline/LayerActivity.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelinePanel.svelte
  src/types/simulation.ts
  src/utilities/gql.ts
Labels: fix

#538 Update Stellar and use new plan left and right arrow icons
  package-lock.json
  package.json
  src/components/simulation/SimulationPanel.svelte
Labels: refactor

#543 Fix for context menu assuming spans exist for a directive
  src/components/timeline/TimelineContextMenu.svelte
  src/types/simulation.ts
  src/utilities/activities.test.ts
  src/utilities/activities.ts
Labels: bug, fix

#548 Update readme image
  docs/images/Full_Example.png
Labels: documentation

#549 Account for simulation bounds in resource layers and timeline histogram
  src/components/timeline/LayerXRange.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelineHistogram.svelte
  src/routes/plans/[id]/+page.svelte
  src/utilities/resources.ts
Labels: fix
