Repository NASA-AMMOS/aerie-ui, pull requests merged in 2023-06, with the labels that each got.

#678 Table and timeline activity double click
  src/components/activity/ActivityDirectivesTable.svelte
  src/components/activity/ActivityDirectivesTablePanel.svelte
  src/components/activity/ActivitySpansTable.svelte
  src/components/activity/ActivitySpansTablePanel.svelte
  src/components/timeline/LayerActivity.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelineContextMenu.svelte
  src/components/timeline/TimelinePanel.svelte
Labels: feature

#674 Expansion Runs UI
  package-lock.json
  package.json
  src/components/expansion/ExpandedSequencesDownloadButton.svelte
  src/components/expansion/ExpansionRuns.svelte
  src/components/sequencing/SequenceEditor.svelte
  src/routes/expansion/+layout.svelte
  src/routes/expansion/runs/+page.svelte
  src/routes/expansion/runs/+page.ts
  src/routes/plans/[id]/+page.svelte
  src/stores/expansion.ts
  src/types/expansion.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: feature

#679 Add page redirection to login when no permissions available
  src/app.d.ts
  src/hooks.server.ts
  src/routes/+layout.ts
  src/routes/constraints/+page.ts
  src/routes/constraints/edit/[id]/+page.ts
  src/routes/constraints/new/+page.ts
  src/routes/dictionaries/+page.ts
  src/routes/expansion/rules/+page.ts
  src/routes/expansion/rules/edit/[id]/+page.ts
  src/routes/expansion/rules/new/+page.ts
  src/routes/expansion/sets/+page.ts
  src/routes/expansion/sets/new/+page.ts
  src/routes/login/+page.svelte
  src/routes/login/+page.ts
  src/routes/models/+page.ts
  src/routes/plans/+page.ts
  src/routes/plans/[id]/+page.ts
  src/routes/plans/[id]/merge/+page.ts
  src/routes/scheduling/+page.ts
  src/routes/scheduling/conditions/edit/[id]/+page.ts
  src/routes/scheduling/conditions/new/+page.ts
  src/routes/scheduling/goals/edit/[id]/+page.ts
  src/routes/scheduling/goals/new/+page.ts
  src/routes/sequencing/+page.ts
  src/routes/sequencing/edit/[id]/+page.ts
  src/routes/sequencing/new/+page.ts
Labels: feature

#681 Add permissions to plan creation page
  package-lock.json
  package.json
  src/app.d.ts
  src/components/context-menu/ContextMenuItem.svelte
  src/components/form/DatePickerField.svelte
  src/components/plan/PlanMergeReview.test.ts
  src/components/ui/DataGrid/DataGridActions.svelte
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
  src/components/ui/DatePicker/DatePicker.svelte
  src/components/ui/DatePicker/DatePickerDropdown.svelte
  src/components/ui/DatePicker/Day.svelte
  src/css/app.css
  src/hooks.server.ts
  src/routes/auth/login/+server.ts
  src/routes/constraints/+page.ts
  src/routes/constraints/edit/[id]/+page.ts
  src/routes/constraints/new/+page.ts
  src/routes/dictionaries/+page.ts
  src/routes/expansion/rules/+page.ts
  src/routes/expansion/rules/edit/[id]/+page.ts
  src/routes/expansion/rules/new/+page.ts
  src/routes/expansion/sets/+page.ts
  src/routes/expansion/sets/new/+page.ts
  src/routes/models/+page.ts
  src/routes/plans/+page.svelte
  src/routes/plans/+page.ts
  src/routes/plans/[id]/+page.ts
  src/routes/plans/[id]/merge/+page.ts
  src/routes/scheduling/+page.ts
  src/routes/scheduling/conditions/edit/[id]/+page.ts
  src/routes/scheduling/conditions/new/+page.ts
  src/routes/scheduling/goals/edit/[id]/+page.ts
  src/routes/scheduling/goals/new/+page.ts
  src/routes/sequencing/+page.ts
  src/routes/sequencing/edit/[id]/+page.ts
  src/routes/sequencing/new/+page.ts
  src/types/activity.ts
  src/types/app.ts
  src/types/permissions.ts
  src/types/plan.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissionHandler.ts
  src/utilities/permissions.ts
  src/utilities/queryPermissions.ts
  src/utilities/useActions.ts
Labels: feature

#689 Add env var to enable or disable the login page
  .env
  src/hooks.server.ts
  src/routes/constraints/+page.ts
  src/routes/constraints/edit/[id]/+page.ts
  src/routes/constraints/new/+page.ts
  src/routes/dictionaries/+page.ts
  src/routes/expansion/rules/+page.ts
  src/routes/expansion/rules/edit/[id]/+page.ts
  src/routes/expansion/rules/new/+page.ts
  src/routes/expansion/runs/+page.ts
  src/routes/expansion/sets/+page.ts
  src/routes/expansion/sets/new/+page.ts
  src/routes/login/+page.ts
  src/routes/models/+page.ts
  src/routes/plans/+page.ts
  src/routes/plans/[id]/+page.ts
  src/routes/plans/[id]/merge/+page.ts
  src/routes/scheduling/+page.ts
  src/routes/scheduling/conditions/edit/[id]/+page.ts
  src/routes/scheduling/conditions/new/+page.ts
  src/routes/scheduling/goals/edit/[id]/+page.ts
  src/routes/scheduling/goals/new/+page.ts
  src/routes/sequencing/+page.ts
  src/routes/sequencing/edit/[id]/+page.ts
  src/routes/sequencing/new/+page.ts
  src/utilities/permissions.ts
Labels: fix

#698 Update DEVELOPER.md
  docs/DEVELOPER.md
Labels: documentation

#703 Merge review fix
  src/components/plan/PlanMergeReview.svelte
  src/components/ui/SearchableDropdown.svelte
Labels: fix

#696 Add permissions to model creation page
  src/components/plan/PlanMergeReview.test.ts
  src/components/scheduling/goals/SchedulingGoalForm.svelte.test.ts
  src/routes/models/+page.svelte
  src/types/model.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: feature

#707 Update stellar to latest version
  package-lock.json
  package.json
Labels: build

#709 Release v1.8.0
  package-lock.json
  package.json
Labels: release

#660 Extended metadata (excluding tags)
  e2e-tests/fixtures/Constraints.ts
  e2e-tests/fixtures/ExpansionRules.ts
  e2e-tests/fixtures/Plans.ts
  src/components/constraints/ConstraintForm.svelte
  src/components/constraints/Constraints.svelte
  src/components/expansion/ExpansionPanel.svelte
  src/components/expansion/ExpansionRuleForm.svelte
  src/components/expansion/ExpansionRules.svelte
  src/components/expansion/ExpansionSetForm.svelte
  src/components/expansion/ExpansionSetRuleSelection.svelte
  src/components/expansion/ExpansionSets.svelte
  src/components/plan/PlanMergeReview.test.ts
  src/components/scheduling/conditions/SchedulingConditionForm.svelte
  src/components/scheduling/conditions/SchedulingConditions.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte.test.ts
  src/components/scheduling/goals/SchedulingGoals.svelte
  src/components/sequencing/SequenceForm.svelte
  src/components/sequencing/Sequences.svelte
  src/components/simulation/SimulationHistoryDataset.svelte
  src/css/ag-grid-stellar.css
  src/routes/expansion/rules/edit/[id]/+page.svelte
  src/routes/models/+page.svelte
  src/routes/plans/+page.svelte
  src/stores/constraints.ts
  src/stores/expansion.ts
  src/stores/scheduling.ts
  src/stores/sequencing.ts
  src/types/constraint.ts
  src/types/expansion.ts
  src/types/model.ts
  src/types/plan.ts
  src/types/scheduling.ts
  src/types/simulation.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/time.test.ts
  src/utilities/time.ts
Labels: feature

#716 Remove unneeded z-index from ag grid cell resize class
  src/css/ag-grid-stellar.css
Labels: fix

#713 Simulation history dataset checkbox fix
  src/components/simulation/SimulationHistoryDataset.svelte
Labels: fix

#705 User role switching
  src/components/app/Nav.svelte
  src/components/plan/PlanMergeReview.svelte
  src/components/plan/PlanMergeReview.test.ts
  src/components/scheduling/goals/SchedulingGoalForm.svelte.test.ts
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
  src/hooks.server.ts
  src/routes/auth/changeRole/+server.ts
  src/routes/auth/login/+server.ts
  src/routes/constraints/+layout.svelte
  src/routes/dictionaries/+page.svelte
  src/routes/expansion/+layout.svelte
  src/routes/expansion/+layout.ts
  src/routes/models/+page.svelte
  src/routes/plans/+page.svelte
  src/routes/plans/[id]/+page.svelte
  src/routes/scheduling/+layout.svelte
  src/routes/sequencing/+layout.svelte
  src/stores/subscribable.ts
  src/types/app.ts
  src/types/auth.ts
  src/utilities/effects.ts
  src/utilities/login.test.ts
  src/utilities/permissions.test.ts
  src/utilities/permissions.ts
  src/utilities/requests.ts
Labels: feature

#724 Upgrade deps to latest
  package-lock.json
  package.json
Labels: build, security

#691 Custom Worker for TypeScript Parameter Validation
  package-lock.json
  package.json
  src/components/expansion/ExpansionLogicEditor.svelte
  src/components/sequencing/SequenceEditor.svelte
  src/components/ui/MonacoEditor.svelte
  src/custom-typings.d.ts
  src/routes/expansion/rules/edit/[id]/+page.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/workers/customCodes.ts
  src/workers/customTS.worker.ts
  src/workers/diagnostics/commandArgumentsDiagnostics.ts
  src/workers/diagnostics/timeDiagnostics.ts
  src/workers/workerHelpers.ts
Labels: feature, sequencing

#726 Fix incorrect User object being used for permissions query
  src/hooks.server.ts
  src/routes/models/+page.svelte
  src/utilities/effects.ts
Labels: fix

#728 Update to accommodate initial tag changes
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/activity/ActivityTypesPanel.svelte
  src/components/timeline/Row.svelte
  src/components/ui/Tags.svelte
  src/stores/activities.ts
  src/types/activity.ts
  src/types/tags.ts
  src/utilities/effects.ts
  src/utilities/generic.test.ts
  src/utilities/generic.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: refactor

#719 Clear selected activity if the active plan changes
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan-merge.test.ts
  e2e-tests/tests/plan.test.ts
  src/routes/plans/[id]/+page.svelte
Labels: fix

#729 Add basic handling of expired JWTs
  src/components/menus/AppMenu.svelte
  src/routes/login/+page.svelte
  src/stores/subscribable.ts
  src/utilities/generic.ts
  src/utilities/login.ts
  src/utilities/permissions.ts
  src/utilities/requests.ts
Labels: fix

#727 Fix tables not updating when user is changed
  src/components/activity/ActivityDirectivesTable.svelte
  src/components/modals/SavedViewsModal.svelte
  src/components/ui/DataGrid/BulkActionDataGrid.svelte
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
  src/components/view/ViewsTable.svelte
  src/routes/models/+page.svelte
  src/routes/plans/+page.svelte
Labels: fix

#739 Fix redundant simulation deletion query preventing plan deletion
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: fix

#733 Add default resource rows
  src/components/timeline/form/TimelineEditorPanel.svelte
  src/routes/plans/[id]/+page.svelte
  src/routes/plans/[id]/+page.ts
  src/stores/resource.ts
  src/stores/simulation.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: feature

#722 Permissions constraints
  src/components/constraints/ConstraintForm.svelte
  src/components/constraints/Constraints.svelte
  src/routes/constraints/+page.svelte
  src/routes/constraints/+page.ts
  src/routes/constraints/edit/[id]/+page.svelte
  src/routes/constraints/edit/[id]/+page.ts
  src/routes/constraints/new/+page.svelte
  src/routes/constraints/new/+page.ts
  src/types/permissions.ts
  src/utilities/effects.ts
  src/utilities/permissions.ts
Labels: feature

#743 Release v1.9.0
  package-lock.json
  package.json
Labels: release

#744 Upgrade deps to latest
  .eslintrc.cjs
  package-lock.json
  package.json
  src/app.d.ts
  src/components/activity/ActivityAnchorForm.svelte
  src/components/activity/ActivityDecomposition.svelte
  src/components/activity/ActivityTableMenu.svelte
  src/components/app/NavButton.svelte
  src/components/console/Console.svelte
  src/components/console/ConsoleDragHandle.svelte
  src/components/console/ConsoleSection.svelte
  src/components/context-menu/ContextMenu.svelte
  src/components/context-menu/ContextMenuItem.svelte
  src/components/expansion/ExpansionPanel.svelte
  src/components/expansion/ExpansionSetRuleSelection.svelte
  src/components/menus/AppMenu.svelte
  src/components/menus/GridMenu.svelte
  src/components/menus/PlanMenu.svelte
  src/components/menus/ViewMenu.svelte
  src/components/modals/CreateViewModal.svelte
  src/components/modals/DeleteActivitiesModal.svelte
  src/components/modals/EditViewModal.svelte
  src/components/modals/Modal.svelte
  src/components/modals/PlanMergeRequestsModal.svelte
  src/components/parameters/ParameterRecStruct.svelte
  src/components/parameters/ValueSourceBadge.svelte
  src/components/plan/PlanMergeReview.svelte
  src/components/plan/PlanNavButton.svelte
  src/components/scheduling/goals/SchedulingGoal.svelte
  src/components/scheduling/goals/SchedulingGoalAnalysesActivities.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/RowDragHandleHeight.svelte
  src/components/timeline/RowDragHandleMove.svelte
  src/components/ui/DataGrid/BulkActionDataGrid.svelte
  src/components/ui/DataGrid/DataGrid.svelte
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
  src/components/ui/DatePicker/Day.svelte
  src/components/ui/DatePicker/Month.svelte
  src/components/ui/ListItem.svelte
  src/components/ui/SearchableDropdown.svelte
  src/components/ui/ToggleableIconButton.svelte
  src/stores/subscribable.ts
  src/utilities/permissionHandler.ts
  vite.config.js
Labels: build

#749 Add permission checks to Command Dictionaries page
  src/routes/dictionaries/+page.svelte
  src/utilities/permissions.ts
Labels: feature

#750 Sequence permissions
  src/components/sequencing/SequenceForm.svelte
  src/components/sequencing/Sequences.svelte
  src/routes/sequencing/edit/[id]/+page.svelte
  src/types/sequencing.ts
  src/utilities/permissions.ts
Labels: feature
