Repository NASA-AMMOS/aerie-ui, pull requests merged in 2023-07, with the labels that each got.

#753 Remove duplicative start and end times from plans table
  src/routes/plans/+page.svelte
Labels: fix

#740 Custom tags input
  package-lock.json
  package.json
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/activity/ActivityFormPanel.svelte
  src/components/plan/PlanMergeReview.svelte
  src/components/plan/PlanMergeReview.test.ts
  src/components/ui/Chip.svelte
  src/components/ui/Tags.svelte
  src/components/ui/Tags.svelte.test.ts
  src/components/ui/Tags/Tag.svelte
  src/components/ui/Tags/Tags.svelte
  src/components/ui/Tags/Tags.svelte.test.ts
  src/stores/activities.ts
  src/stores/tags.ts
  src/types/plan.ts
  src/utilities/color.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: feature

#758 Add environment variable doc
  docs/ENVIRONMENT.md
Labels: documentation

#760 Revert TypeScript to previous version
  package-lock.json
  package.json
Labels: build

#755 Plan management panel with tag editing
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan.test.ts
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/menus/GridMenu.svelte
  src/components/plan/PlanForm.svelte
  src/components/plan/PlanManagementPanel.svelte
  src/components/plan/PlanMergeReview.test.ts
  src/components/ui/Chip.svelte
  src/components/ui/DataGrid/DataGrid.svelte
  src/components/ui/DataGrid/DataGridTagsCellRenderer.ts
  src/components/ui/PlanGrid.svelte
  src/components/ui/Tags/Tags.svelte
  src/routes/plans/+page.svelte
  src/routes/plans/[id]/+page.svelte
  src/routes/plans/[id]/+page.ts
  src/stores/plan.ts
  src/types/plan.ts
  src/types/tags.ts
  src/types/view.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: feature

#735 Custom Worker - TS AST Repeated Argument Checking
  src/workers/workerHelpers.ts
Labels: feature, sequencing

#754 Add permissions to Activity Directives Table and Types Panels
  src/components/activity/ActivityAnchorForm.svelte
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/activity/ActivityDirectivesTable.svelte
  src/components/activity/ActivityDirectivesTablePanel.svelte
  src/components/activity/ActivityFormPanel.svelte
  src/components/activity/ActivityPresetInput.svelte
  src/components/activity/ActivityTypesPanel.svelte
  src/components/menus/MenuItem.svelte
  src/components/parameters/ParameterBase.svelte
  src/components/parameters/ParameterBaseBoolean.svelte
  src/components/parameters/ParameterBaseDuration.svelte
  src/components/parameters/ParameterBaseNumber.svelte
  src/components/parameters/ParameterBasePath.svelte
  src/components/parameters/ParameterBaseRightAdornments.svelte
  src/components/parameters/ParameterBaseString.svelte
  src/components/parameters/ParameterBaseVariant.svelte
  src/components/parameters/ParameterRec.svelte
  src/components/parameters/ParameterRecSeries.svelte
  src/components/parameters/ParameterRecStruct.svelte
  src/components/parameters/Parameters.svelte
  src/components/parameters/ValueSourceBadge.svelte
  src/components/ui/DataGrid/BulkActionDataGrid.svelte
  src/components/ui/EditableDropdown.svelte
  src/components/ui/ListItem.svelte
  src/components/ui/SearchableDropdown.svelte
  src/types/dropdown.ts
  src/utilities/permissionHandler.ts
  src/utilities/permissions.test.ts
  src/utilities/permissions.ts
Labels: feature

#762 fix some `strict: true` linting errors
  src/components/constraints/ConstraintEditor.svelte
  src/stores/activities.ts
  src/utilities/color.ts
Labels: refactor

#764 Add permission to model create button
  src/routes/models/+page.svelte
Labels: feature

#771 Release v1.10.0
  package-lock.json
  package.json
Labels: release

#773 Add permissions to Expansion panel
  src/components/expansion/ExpansionPanel.svelte
  src/components/ui/PanelHeaderActionButton.svelte
  src/utilities/permissions.ts
Labels: feature

#765 Tags for plan creation, constraint, and expansion rules
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan.test.ts
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/constraints/ConstraintForm.svelte
  src/components/constraints/Constraints.svelte
  src/components/expansion/ExpansionRuleForm.svelte
  src/components/expansion/ExpansionRules.svelte
  src/components/expansion/ExpansionSetForm.svelte
  src/components/expansion/ExpansionSetRuleSelection.svelte
  src/components/expansion/ExpansionSets.svelte
  src/components/menus/GridMenu.svelte
  src/components/plan/PlanForm.svelte
  src/components/plan/PlanMetadataPanel.svelte
  src/components/ui/Chip.svelte
  src/components/ui/PlanGrid.svelte
  src/components/ui/Tags/Tags.svelte
  src/css/app.css
  src/routes/constraints/edit/[id]/+page.svelte
  src/routes/constraints/new/+page.svelte
  src/routes/expansion/rules/edit/[id]/+page.svelte
  src/routes/plans/+page.svelte
  src/stores/expansion.ts
  src/stores/tags.ts
  src/types/activity.ts
  src/types/constraint.ts
  src/types/expansion.ts
  src/types/plan.ts
  src/types/tags.ts
  src/types/view.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
  src/utilities/tags.ts
Labels: feature

#761 Custom Worker- EPOCH HMS String Parsing should support Negative Duration.
  src/workers/customCodes.ts
  src/workers/diagnostics/timeDiagnostics.ts
Labels: feature, sequencing

#775 Add permissions to Simulations panel
  src/components/activity/ActivityPresetInput.svelte
  src/components/parameters/ParameterBasePath.svelte
  src/components/simulation/SimulationPanel.svelte
  src/components/simulation/SimulationTemplateInput.svelte
  src/stores/simulation.ts
  src/types/simulation.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: feature

#789 Update permissions for aerie_admin changes
  .prettierignore
  e2e-tests/fixtures/ExpansionSets.ts
  e2e-tests/tests/plan-simulation-templates.test.ts
  e2e-tests/tests/plan.test.ts
  src/types/scheduling.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: refactor

#788 Update the admin constant to be consistent with the backend
  src/components/plan/PlanMergeReview.test.ts
  src/components/scheduling/goals/SchedulingGoalForm.svelte.test.ts
  src/types/app.ts
  src/utilities/login.test.ts
  src/utilities/permissions.test.ts
  src/utilities/permissions.ts
Labels: refactor

#784 Scheduling goal tag editing and display
  src/components/expansion/ExpansionRuleForm.svelte
  src/components/scheduling/Scheduling.svelte
  src/components/scheduling/goals/SchedulingGoal.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/scheduling/goals/SchedulingGoals.svelte
  src/routes/scheduling/goals/edit/[id]/+page.svelte
  src/stores/scheduling.ts
  src/types/scheduling.ts
  src/types/tags.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: feature

#779 Add permissions to Timeline panel
  src/components/timeline/LayerActivity.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelineContextMenu.svelte
  src/components/timeline/TimelineLockControl.svelte
  src/components/timeline/TimelinePanel.svelte
  src/types/permissions.ts
  src/utilities/effects.ts
Labels: feature

#791 Fix issue where CSS classes are lost when permissions change
  src/utilities/permissionHandler.ts
Labels: fix

#787 Fix lint errors not already addressed in Timeline related files
  src/components/timeline/ConstraintViolations.svelte
  src/components/timeline/LayerGaps.svelte
  src/components/timeline/LayerLine.svelte
  src/components/timeline/LayerXRange.svelte
  src/components/timeline/RowXAxisTicks.svelte
  src/components/timeline/RowYAxes.svelte
  src/components/timeline/TimelineCursors.svelte
  src/components/timeline/TimelineHistogram.svelte
  src/components/timeline/TimelineSimulationRange.svelte
  src/components/timeline/TimelineViewControls.svelte
  src/components/timeline/Tooltip.svelte
  src/components/timeline/XAxis.svelte
  src/components/timeline/form/TimelineEditorLayerFilter.svelte
  src/components/timeline/form/TimelineEditorLayerSelectedFilters.svelte
  src/components/timeline/form/TimelineEditorPanel.svelte
  src/components/timeline/form/YAxisForm.svelte
  src/stores/views.ts
  src/utilities/activities.ts
  src/utilities/timeline.ts
Labels: refactor

#790 Implement Permissions on Scheduling Page
  src/components/scheduling/Scheduling.svelte
  src/components/scheduling/conditions/SchedulingConditionForm.svelte
  src/components/scheduling/conditions/SchedulingConditions.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte.test.ts
  src/components/scheduling/goals/SchedulingGoals.svelte
  src/routes/scheduling/+page.svelte
  src/routes/scheduling/+page.ts
  src/types/plan.ts
  src/types/scheduling.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: feature

#795 Implement permissions for scheduling goal/conditions panels
  src/components/scheduling/SchedulingConditionsPanel.svelte
  src/components/scheduling/SchedulingGoalsPanel.svelte
  src/components/scheduling/conditions/SchedulingCondition.svelte
  src/components/scheduling/goals/SchedulingGoal.svelte
  src/utilities/permissions.ts
Labels: feature

#796 Add permissions to plan constraints panel
  src/components/constraints/ConstraintListItem.svelte
  src/components/constraints/ConstraintsPanel.svelte
  src/utilities/permissions.ts
Labels: feature

#793 Add permissions to plan merge
  src/components/activity/ActivityDirectiveSourceForm.svelte
  src/components/menus/PlanMenu.svelte
  src/components/modals/PlanMergeRequestsModal.svelte
  src/components/plan/PlanMergeReview.svelte
  src/components/plan/PlanMergeReview.test.ts
  src/types/permissions.ts
  src/types/plan.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: feature

#798 Plan nav header permissions
  src/components/expansion/ExpansionRules.svelte
  src/components/menus/MenuItem.svelte
  src/components/menus/ViewMenu.svelte
  src/components/modals/SavedViewsModal.svelte
  src/components/plan/PlanNavButton.svelte
  src/components/view/ViewsTable.svelte
  src/routes/plans/+page.svelte
  src/routes/plans/[id]/+page.svelte
  src/types/modal.ts
  src/utilities/modal.ts
  src/utilities/permissions.ts
Labels: feature

#801 Turn on `strict: true` for typescript
  src/components/activity/ActivityDecomposition.svelte
  src/components/activity/ActivitySpanForm.svelte
  src/components/activityMetadata/ActivityMetadataBaseEnumMultiselect.svelte
  src/components/activityMetadata/ActivityMetadataField.svelte
  src/components/constraints/ConstraintsPanel.svelte
  src/components/context-menu/ContextSubMenuItem.svelte
  src/components/expansion/ExpansionSetRuleSelection.svelte
  src/components/form/ColorSchemePicker.svelte
  src/components/form/Field.svelte
  src/components/form/Input.svelte
  src/components/menus/PlanMenu.svelte
  src/components/modals/DeleteActivitiesModal.svelte
  src/components/modals/EditViewModal.svelte
  src/components/modals/ExpansionSequenceModal.svelte
  src/components/modals/PlanBranchRequestModal.svelte
  src/components/parameters/ParameterRecSeries.svelte
  src/components/parameters/ParameterRecStruct.svelte
  src/components/scheduling/SchedulingConditionsPanel.svelte
  src/components/scheduling/SchedulingGoalsPanel.svelte
  src/components/scheduling/conditions/SchedulingConditionForm.svelte
  src/components/scheduling/conditions/SchedulingConditions.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/scheduling/goals/SchedulingGoals.svelte
  src/components/timeline/LayerActivity.svelte
  src/components/ui/CssGrid.svelte
  src/components/ui/DatePicker/DatePicker.svelte.test.ts
  src/components/ui/IFrame.svelte
  src/components/ui/IFramePanel.svelte
  src/components/ui/MonacoEditor.svelte
  src/components/ui/Tabs/Tabs.svelte
  src/routes/auth/logout/+server.ts
  src/routes/view/validate/+server.ts
  src/stores/constraints.ts
  src/stores/subscribable.ts
  src/types/activity.ts
  src/types/form.ts
  src/utilities/activities.test.ts
  src/utilities/activities.ts
  src/utilities/effects.ts
  src/utilities/generic.ts
  src/utilities/requests.ts
  src/utilities/status.ts
  src/utilities/toast.ts
  src/utilities/view.ts
  src/workers/customTS.worker.ts
  src/workers/diagnostics/commandArgumentsDiagnostics.ts
  src/workers/workerHelpers.ts
  tsconfig.json
Labels: refactor

#804 Fix editable behavior for plan creation tag input
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/constraints/ConstraintForm.svelte
  src/components/expansion/ExpansionRuleForm.svelte
  src/components/plan/PlanForm.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/ui/Tags/Tags.svelte
  src/routes/plans/+page.svelte
Labels: fix

#805 Disable events in child elements for permission disabled components
  src/css/app.css
Labels: fix

#809 Release v1.11.0
  package-lock.json
  package.json
Labels: release

#812 Close the "plan locked" warning modal if the page is navigated away from
  src/routes/plans/[id]/+page.svelte
  src/utilities/modal.ts
Labels: fix

#815 Destroy modal component on close to unload window listeners
  src/utilities/modal.ts
Labels: fix
