Repository NASA-AMMOS/aerie-ui, pull requests merged in 2023-04, with the labels that each got.

#553 Fix Datepicker unit test
  src/components/ui/DatePicker/DatePicker.svelte.test.ts
Labels: test

#552 Release v1.4.0
  package-lock.json
  package.json
Labels: release

#539 Delete Anchored Directives UI
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan-activities.test.ts
  e2e-tests/tests/plan.test.ts
  src/assets/delete-anchored-activities.svg
  src/assets/reanchor-to-nearest-parent.svg
  src/assets/reanchor-to-plan-start.svg
  src/components/modals/DeleteActivitiesModal.svelte
  src/components/ui/ActivityDirectiveIcon.svelte
  src/types/activity.ts
  src/utilities/activities.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/modal.ts
Labels: feature

#555 Add css class name kebab case lint rule
  .stylelintrc
  e2e-tests/fixtures/Plan.ts
  src/components/plan/PlanNavButton.svelte
  src/components/ui/DatePicker/Day.svelte
  src/components/ui/DatePicker/Day.svelte.test.ts
  src/components/ui/Panel.svelte
  src/components/ui/StatusBadge.svelte
Labels: style, refactor

#557 Sample profiles using profile duration
  src/routes/plans/[id]/+page.svelte
  src/utilities/effects.ts
  src/utilities/resources.test.ts
  src/utilities/resources.ts
Labels: fix

#561 Refactor generateDefaultView and view validation
  src/routes/view/validate/+server.ts
  src/utilities/effects.ts
  src/utilities/timeline.ts
  src/utilities/view.test.ts
  src/utilities/view.ts
Labels: fix

#550 Simulation time range visualization
  package-lock.json
  package.json
  src/components/context-menu/ContextMenuSeparator.svelte
  src/components/context-menu/ContextSubMenuItem.svelte
  src/components/simulation/SimulationHistoryDataset.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelineContextMenu.svelte
  src/components/timeline/TimelinePanel.svelte
  src/components/timeline/TimelineSimulationRange.svelte
  src/components/timeline/TimelineSimulationRangeCursor.svelte
Labels: feature

#564 Ensure activity directive start_offset is not earlier than plan start
  src/components/timeline/LayerActivity.svelte
Labels: fix

#571 Explicitly check that the subFormParameter value is not null
  src/components/parameters/ParameterRecStruct.svelte
Labels: bug, fix

#572 Add context menu item to toggle simulation of scheduling goals
  src/components/scheduling/SchedulingGoalsPanel.svelte
  src/components/scheduling/goals/SchedulingGoal.svelte
  src/types/scheduling.ts
  src/utilities/gql.ts
Labels: feature

#562 Simulation Templates UI
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan-activity-presets.test.ts
  e2e-tests/tests/plan-simulation-templates.test.ts
  e2e-tests/tests/plan.test.ts
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/activity/ActivityPresetInput.svelte
  src/components/activity/ActivityPresetInput.svelte.test.ts
  src/components/parameters/ParameterBase.svelte
  src/components/parameters/ParameterBaseBoolean.svelte
  src/components/parameters/ParameterBaseDuration.svelte
  src/components/parameters/ParameterBaseNumber.svelte
  src/components/parameters/ParameterBasePath.svelte
  src/components/parameters/ParameterBaseRightAdornments.svelte
  src/components/parameters/ParameterBaseString.svelte
  src/components/parameters/ParameterBaseVariant.svelte
  src/components/parameters/ParameterRec.svelte
  src/components/parameters/ParameterRecSeries.svelte
  src/components/parameters/ParameterRecStruct.svelte
  src/components/parameters/Parameters.svelte
  src/components/parameters/ValueSourceBadge.svelte
  src/components/simulation/SimulationPanel.svelte
  src/components/simulation/SimulationTemplateInput.svelte
  src/components/ui/DatePicker/DatePickerDropdown.svelte
  src/components/ui/EditableDropdown.svelte
  src/components/ui/EditableDropdown.svelte.test.ts
  src/components/ui/SearchableDropdown.svelte
  src/components/ui/SearchableDropdown.svelte.test.ts
  src/types/datepicker.ts
  src/types/dropdown.ts
  src/types/parameter.ts
  src/types/simulation.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/parameters.test.ts
  src/utilities/parameters.ts
Labels: feature

#594 Release v1.5.0
  package-lock.json
  package.json
Labels: release

#573 Utilize new SearchableDropdown for anchor selection
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan-activities.test.ts
  e2e-tests/tests/plan-activity-presets.test.ts
  src/components/activity/ActivityAnchorForm.svelte
Labels: refactor

#595 Fix for histogram rendering when directive/span start matches plan end time
  src/components/timeline/TimelineHistogram.svelte
Labels: bug, fix

#597 Add issue templates
  .github/ISSUE_TEMPLATE/1-bug_report.yml
  .github/ISSUE_TEMPLATE/2-feature_request.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#610 Add `strict` flag to tsconfig for convenience
  tsconfig.json
Labels: refactor
