Repository NASA-AMMOS/aerie-ui, pull requests merged in 2023-11, with the labels that each got.

#975 Fix login redirect
  src/hooks.server.ts
  src/routes/+layout.server.ts
  src/routes/constraints/+page.ts
  src/routes/constraints/edit/[id]/+page.ts
  src/routes/constraints/new/+page.ts
  src/routes/dictionaries/+page.ts
  src/routes/expansion/rules/+page.ts
  src/routes/expansion/rules/edit/[id]/+page.ts
  src/routes/expansion/rules/new/+page.ts
  src/routes/expansion/runs/+page.ts
  src/routes/expansion/sets/+page.ts
  src/routes/expansion/sets/new/+page.ts
  src/routes/models/+page.ts
  src/routes/plans/+page.ts
  src/routes/plans/[id]/+page.ts
  src/routes/plans/[id]/merge/+page.ts
  src/routes/scheduling/+page.ts
  src/routes/scheduling/conditions/edit/[id]/+page.ts
  src/routes/scheduling/conditions/new/+page.ts
  src/routes/scheduling/goals/edit/[id]/+page.ts
  src/routes/scheduling/goals/new/+page.ts
  src/routes/sequencing/+page.ts
  src/routes/sequencing/edit/[id]/+page.ts
  src/routes/sequencing/new/+page.ts
  src/routes/tags/+page.ts
  src/utilities/requests.ts
Labels: bug

#985 Release v2.0.0
  package-lock.json
  package.json
Labels: release

#990 enable strict equal lint rule
  .eslintrc.cjs
  src/components/activity/ActivityDirectiveChangelog.svelte
  src/components/activity/ActivityFormPanel.svelte
  src/utilities/modal.ts
  src/utilities/useActions.ts
  src/workers/workerHelpers.ts
Labels: refactor

#989 Debounce parameter form number inputs
  src/components/parameters/ParameterBaseNumber.svelte
Labels: fix

#988 Proper truncation of row names in timeline editor
  src/components/timeline/form/TimelineEditorPanel.svelte
Labels: fix

#987 Ensure getPlanTags returns an array if no tags found
  src/utilities/effects.ts
Labels: fix

#977 Timeline density improvements and refactoring
  package-lock.json
  package.json
  src/components/app/Nav.svelte
  src/components/context-menu/ContextMenu.svelte
  src/components/context-menu/ContextMenuItem.svelte
  src/components/simulation/SimulationPanel.svelte
  src/components/timeline/LayerActivity.svelte
  src/components/timeline/LayerLine.svelte
  src/components/timeline/LayerXRange.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/RowDragHandleHeight.svelte
  src/components/timeline/RowHeader.svelte
  src/components/timeline/RowHeaderDragHandleWidth.svelte
  src/components/timeline/RowHeaderMenu.svelte
  src/components/timeline/RowXAxisTicks.svelte
  src/components/timeline/RowYAxes.svelte
  src/components/timeline/RowYAxisTicks.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelineContextMenu.svelte
  src/components/timeline/TimelineCursors.svelte
  src/components/timeline/TimelineHistogram.svelte
  src/components/timeline/TimelinePanel.svelte
  src/components/timeline/TimelineSimulationRange.svelte
  src/components/timeline/TimelineSimulationRangeCursor.svelte
  src/components/timeline/TimelineTimeDisplay.svelte
  src/components/timeline/Tooltip.svelte
  src/components/timeline/XAxis.svelte
  src/components/timeline/form/LayerLineForm.svelte
  src/components/timeline/form/LayerXRangeForm.svelte
  src/components/timeline/form/TimelineEditorLayerSettings.svelte
  src/components/timeline/form/TimelineEditorPanel.svelte
  src/components/ui/CssGridGutter.svelte
  src/enums/view.ts
  src/schemas/ui-view-schema.json
  src/stores/simulation.ts
  src/types/timeline.ts
  src/utilities/effects.ts
  src/utilities/time.ts
  src/utilities/timeline.test.ts
  src/utilities/timeline.ts
  src/utilities/view.ts
Labels: feature

#997 Do not hide bottom row border when row has auto height
  src/components/timeline/Row.svelte
Labels: fix

#998 Fix local time display
  src/components/timeline/Timeline.svelte
Labels: fix

#1003 Make drag handles follow cursor more closely
  src/components/console/ConsoleDragHandle.svelte
  src/components/timeline/RowDragHandleHeight.svelte
  src/components/timeline/RowHeaderDragHandleWidth.svelte
Labels: refactor

#1014 Release v2.1.0
  package-lock.json
  package.json
Labels: release

#1015 Fixes the number of directives displayed associated with snapshot
  src/routes/plans/[id]/+page.svelte
Labels: fix

#1020 Fix Activity Preset Update Failing
  src/components/activity/ActivityDirectiveForm.svelte
  src/types/activity.ts
  src/utilities/effects.ts
Labels: fix

#1033 Fix concurrent test worker login failure
  e2e-tests/fixtures/PlaywrightTest.ts
  e2e-tests/fixtures/global.setup.ts
  e2e-tests/fixtures/global.teardown.ts
  e2e-tests/tests/app-nav.test.ts
  e2e-tests/tests/constraints.test.ts
  e2e-tests/tests/dictionaries.test.ts
  e2e-tests/tests/expansion.test.ts
  e2e-tests/tests/models.test.ts
  e2e-tests/tests/plan-activities.test.ts
  e2e-tests/tests/plan-activity-presets.test.ts
  e2e-tests/tests/plan-merge.test.ts
  e2e-tests/tests/plan-simulation-templates.test.ts
  e2e-tests/tests/plan.test.ts
  e2e-tests/tests/plans.test.ts
  e2e-tests/tests/routes.test.ts
  e2e-tests/tests/scheduling.test.ts
  e2e-tests/tests/timeline-view-editing.test.ts
  playwright.config.ts
Labels: refactor

#1031 Add toggle to autosize activity table columns
  src/components/activity/ActivityDirectivesTable.svelte
  src/components/activity/ActivityDirectivesTablePanel.svelte
  src/components/activity/ActivitySpansTable.svelte
  src/components/activity/ActivitySpansTablePanel.svelte
  src/components/ui/DataGrid/BulkActionDataGrid.svelte
  src/components/ui/DataGrid/DataGrid.svelte
  src/schemas/ui-view-schema.json
  src/types/view.ts
  src/utilities/view.ts
Labels: refactor
