Repository NASA-AMMOS/aerie-ui, pull requests merged in 2023-12, with the labels that each got.

#1022 Add Constraint Compile Icon
  src/components/constraints/ConstraintListItem.svelte
  src/components/constraints/ConstraintsPanel.svelte
  src/components/timeline/TimelineHistogram.svelte
  src/components/timeline/Tooltip.svelte
  src/stores/constraints.ts
  src/types/constraint.ts
  src/utilities/gql.ts
Labels: constraints

#1016 X-Range performance improvements
  src/components/timeline/LayerXRange.svelte
Labels: performance

#1054 Set correct path for uploaded file in sim config
  .env
  docs/ENVIRONMENT.md
  src/components/simulation/SimulationPanel.svelte
  src/utilities/effects.test.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: fix

#1017 Loading indicator for line and x-range layers
  src/components/timeline/Row.svelte
  src/routes/plans/[id]/+page.svelte
  src/stores/simulation.ts
  src/utilities/effects.ts
Labels: feature

#1060 Release v2.2.0
  package-lock.json
  package.json
Labels: release

#1065 Release v2.2.0
  package-lock.json
  package.json
Labels: release

#1066 Take "out of plan bounds" activities into account in total count display
  src/components/menus/ActivityStatusMenu.svelte
  src/routes/plans/[id]/+page.svelte
Labels: fix
