Repository NASA-AMMOS/aerie-ui, pull requests merged in 2023-05, with the labels that each got.

#612 Release v1.6.0
  package-lock.json
  package.json
Labels: release

#618 Remove 'summary' section from constraints
  e2e-tests/fixtures/Constraints.ts
  src/components/constraints/ConstraintForm.svelte
  src/routes/constraints/edit/[id]/+page.svelte
  src/types/constraint.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: refactor, fix

#609 Add derived start to directives table and derived start/end to spans table
  src/components/activity/ActivityDirectivesTablePanel.svelte
  src/components/activity/ActivitySpansTablePanel.svelte
  src/utilities/generic.test.ts
  src/utilities/generic.ts
  src/utilities/time.test.ts
  src/utilities/time.ts
  src/utilities/view.ts
Labels: feature

#569 Turn on JWT auth
  .env
  .github/workflows/test.yml
  .gitignore
  docker-compose-test.yml
  docs/DEVELOPER.md
  e2e-tests/fixtures/PlaywrightTest.ts
  e2e-tests/tests/app-nav.test.ts
  e2e-tests/tests/constraints.test.ts
  e2e-tests/tests/dictionaries.test.ts
  e2e-tests/tests/expansion.test.ts
  e2e-tests/tests/models.test.ts
  e2e-tests/tests/plan-activities.test.ts
  e2e-tests/tests/plan-activity-presets.test.ts
  e2e-tests/tests/plan-merge.test.ts
  e2e-tests/tests/plan-simulation-templates.test.ts
  e2e-tests/tests/plan.test.ts
  e2e-tests/tests/plans.test.ts
  e2e-tests/tests/routes.test.ts
  e2e-tests/tests/scheduling.test.ts
  e2e-tests/tests/timeline-view-editing.test.ts
  src/hooks.server.ts
  src/routes/auth/login/+server.ts
  src/routes/auth/logout/+server.ts
  src/stores/subscribable.ts
  src/types/app.ts
  src/types/auth.ts
  src/utilities/effects.ts
  src/utilities/requests.ts
Labels: feature, breaking change

#620 Use custom Collapse component instead of native details and summary elements
  e2e-tests/tests/plan-activities.test.ts
  e2e-tests/tests/plan-simulation-templates.test.ts
  src/components/Collapse.svelte
  src/components/activity/ActivityAnchorForm.svelte
  src/components/activity/ActivityAnchorForm.svelte.test.ts
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/activity/ActivitySpanForm.svelte
  src/components/expansion/ExpansionPanel.svelte
  src/components/parameters/ParameterBaseVariant.svelte
  src/components/parameters/ParameterName.svelte
  src/components/parameters/ParameterRecSeries.svelte
  src/components/parameters/ParameterRecStruct.svelte
  src/components/plan/PlanMergeReview.svelte
  src/components/simulation/SimulationPanel.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/form/TimelineEditorLayerSelectedFilters.svelte
  src/css/app.css
  src/stores/simulation.ts
Labels: refactor

#599 Constraints panel refactor
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan.test.ts
  src/components/CollapsibleListControls.svelte
  src/components/constraints/ConstraintListItem.svelte
  src/components/constraints/ConstraintViolationButton.svelte
  src/components/constraints/ConstraintViolationsPanel.svelte
  src/components/constraints/ConstraintsPanel.svelte
  src/components/menus/GridMenu.svelte
  src/components/scheduling/SchedulingConditionsPanel.svelte
  src/components/scheduling/SchedulingGoalsPanel.svelte
  src/components/scheduling/conditions/SchedulingCondition.svelte
  src/components/scheduling/goals/SchedulingGoal.svelte
  src/components/scheduling/goals/SchedulingGoalAnalysesActivities.svelte
  src/components/scheduling/goals/SchedulingGoalAnalysesBadge.svelte
  src/components/timeline/TimelinePanel.svelte
  src/components/ui/PanelHeaderActionButton.svelte
  src/components/ui/PlanGrid.svelte
  src/schemas/ui-view-schema.json
  src/stores/constraints.ts
  src/types/constraint.ts
  src/types/view.ts
  src/utilities/effects.ts
  src/utilities/time.test.ts
  src/utilities/time.ts
Labels: refactor

#627 Fix DataGrid `strict:true` errors
  src/components/activity/ActivityDirectivesTable.svelte
  src/components/activity/ActivityDirectivesTablePanel.svelte
  src/components/activity/ActivitySpansTable.svelte
  src/components/activity/ActivitySpansTablePanel.svelte
  src/components/activity/ActivityTableMenu.svelte
  src/components/constraints/Constraints.svelte
  src/components/expansion/ExpansionPanel.svelte
  src/components/expansion/ExpansionRules.svelte
  src/components/expansion/ExpansionSetForm.svelte
  src/components/expansion/ExpansionSets.svelte
  src/components/scheduling/conditions/SchedulingConditions.svelte
  src/components/scheduling/goals/SchedulingGoals.svelte
  src/components/sequencing/Sequences.svelte
  src/components/ui/DataGrid/BulkActionDataGrid.svelte
  src/components/ui/DataGrid/DataGrid.svelte
  src/components/ui/DataGrid/DataGridActions.svelte
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
  src/components/view/ViewsTable.svelte
  src/routes/dictionaries/+page.svelte
  src/routes/models/+page.svelte
  src/routes/plans/+page.svelte
Labels: refactor

#607 Render external dataset with profile gaps
  src/components/timeline/LayerGaps.svelte
  src/components/timeline/LayerLine.svelte
  src/components/timeline/LayerXRange.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Tooltip.svelte
  src/types/simulation.ts
  src/types/timeline.ts
  src/utilities/resources.test.ts
  src/utilities/resources.ts
Labels: feature

#631 Update test compose with new env vars
  docker-compose-test.yml
Labels: refactor

#619 Improve simulated activity timeline rendering
  src/components/timeline/LayerActivity.svelte
  src/types/timeline.ts
Labels: feature

#632 Fix searchable dropdown
  src/components/activity/ActivityAnchorForm.svelte
  src/components/ui/SearchableDropdown.svelte
Labels: fix

#643 Add disableable default resize behavior to tables
  src/components/activity/ActivityDirectivesTable.svelte
  src/components/activity/ActivitySpansTable.svelte
  src/components/ui/DataGrid/BulkActionDataGrid.svelte
  src/components/ui/DataGrid/DataGrid.svelte
  src/components/ui/DataGrid/DataGrid.test.ts
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
Labels: refactor

#626 Toggle directive rendering on timeline
  src/components/timeline/LayerActivity.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelinePanel.svelte
  src/components/timeline/TimelineViewControls.svelte
  src/components/timeline/TimelineViewDirectiveControls.svelte
  src/components/ui/ActivityDirectiveIcon.svelte
  src/components/ui/ToggleableIconButton.svelte
  src/types/timeline.ts
Labels: feature

#645 Update GQL playground link to Gateway
  e2e-tests/fixtures/AppNav.ts
  e2e-tests/tests/app-nav.test.ts
  src/components/menus/AppMenu.svelte
Labels: refactor

#648 Release v1.7.0
  package-lock.json
  package.json
Labels: release

#651 Use new resource_type table instead of action
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: refactor

#625 Implement Custom TS Worker
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/sequencing/SequenceEditor.svelte
  src/components/ui/MonacoEditor.svelte
  src/custom-typings.d.ts
  src/types/monaco-internal.ts
  src/utilities/generic.ts
  src/workers/customTS.worker.ts
  src/workers/sequencingDiagnostics.ts
  static/.gitignore
  vite.config.js
  vite.worker-build-plugin.js
Labels: build

#653 Fix issue with command dictionary creation
  src/routes/dictionaries/+page.svelte
  src/routes/plans/[id]/+page.svelte
  src/stores/expansion.ts
  src/utilities/effects.ts
Labels: fix

#652 Fix Breaking Changes from Hasura Auth PR
  e2e-tests/tests/plan-merge.test.ts
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/modals/PlanMergeRequestsModal.svelte
  src/types/activity.ts
  src/types/sequencing.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: refactor

#663 Remove version store
  src/components/modals/AboutModal.svelte
  src/routes/+layout.ts
  src/stores/app.ts
Labels: refactor

#664 Put app in SPA mode for now
  src/components/menus/PlanMenu.svelte
  src/routes/+layout.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: refactor

#661 Updated the constraint violation query to match the new structure
  src/stores/constraints.ts
  src/types/constraint.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: refactor
