Repository NASA-AMMOS/aerie-ui, pull requests merged in 2023-09, with the labels that each got.

#881 Sort Start Offset column chronologically
  src/components/activity/ActivityDirectivesTablePanel.svelte
Labels: fix

#882 Add columns for model name and version
  src/routes/plans/+page.svelte
Labels: feature

#866 Implement Quick Fix Popover
  src/components/expansion/ExpansionLogicEditor.svelte
  src/components/sequencing/SequenceEditor.svelte
  src/components/ui/MonacoEditor.svelte
  src/utilities/monacoHelper.ts
  src/workers/customCodes.ts
  src/workers/diagnostics/timeDiagnostics.ts
Labels: feature, sequencing

#884 Release v1.13.0
  package-lock.json
  package.json
Labels: release

#890 Remove logout to be in line with Gateway
  src/routes/auth/logout/+server.ts
  src/types/app.ts
  src/types/auth.ts
  src/utilities/effects.ts
Labels: refactor, gateway

#891 Store active role in cookie instead of token
  src/hooks.server.ts
  src/routes/auth/changeRole/+server.ts
  src/routes/auth/login/+server.ts
  src/routes/auth/logout/+server.ts
  src/types/app.ts
  src/utilities/effects.ts
Labels: refactor

#808 Show simulation progress
  src/components/constraints/ConstraintsPanel.svelte
  src/components/form/ColorPresetsPicker.svelte
  src/components/modals/DeleteActivitiesModal.svelte
  src/components/plan/PlanNavButton.svelte
  src/components/simulation/SimulationHistoryDataset.svelte
  src/components/simulation/SimulationPanel.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/TimelineLockControl.svelte
  src/components/ui/ProgressLinear.svelte
  src/components/ui/ProgressRadial.svelte
  src/components/ui/StatusBadge.svelte
  src/components/ui/UserBadge.svelte
  src/css/stellar.css
  src/routes/plans/[id]/+page.svelte
  src/stores/simulation.ts
  src/types/errors.ts
  src/types/simulation.ts
  src/utilities/effects.ts
  src/utilities/generic.ts
  src/utilities/gql.ts
  src/utilities/modal.ts
  src/utilities/permissions.ts
  src/utilities/simulation.ts
  src/utilities/status.ts
Labels: feature, simulation

#885 Create and restore plan snapshots
  .eslintrc.cjs
  src/components/menus/PlanMenu.svelte
  src/components/modals/CreatePlanSnapshotModal.svelte
  src/components/modals/RestorePlanSnapshotModal.svelte
  src/components/modals/SavedViewsModal.svelte
  src/enums/searchParameters.ts
  src/routes/login/+page.svelte
  src/routes/plans/+page.svelte
  src/routes/plans/[id]/+page.svelte
  src/routes/plans/[id]/+page.ts
  src/routes/scheduling/conditions/new/+page.ts
  src/routes/scheduling/goals/new/+page.ts
  src/stores/planSnapshots.ts
  src/types/activity.ts
  src/types/permissions.ts
  src/types/plan-snapshot.ts
  src/utilities/effects.ts
  src/utilities/generic.test.ts
  src/utilities/generic.ts
  src/utilities/gql.ts
  src/utilities/modal.ts
  src/utilities/permissions.ts
Labels: feature

#896 Custom Worker - Warning when use of identifiers.
  src/workers/customCodes.ts
  src/workers/workerHelpers.ts
Labels: bug, fix

#904 Column to show applied presets
  src/components/activity/ActivityDirectivesTablePanel.svelte
  src/utilities/view.ts
Labels: feature
