Repository NASA-AMMOS/aerie-ui, pull requests merged in 2023-01, with the labels that each got.

#323 Use new table column icons
  package-lock.json
  package.json
  src/components/activity/ActivityTablePanel.svelte
  src/components/ui/DataGrid/column-menu/ColumnResizeContextMenu.svelte
Labels: feature

#322 Add multi-arch image build, update action versions
  .github/workflows/publish.yml
Labels: ci

#327 Add buttons to clear console errors
  src/components/console/ConsoleSection.svelte
  src/routes/plans/[id]/+page.svelte
  src/stores/errors.ts
  src/utilities/effects.ts
Labels: feature

#326 Prevent duplicate toast messages from filling screen
  src/utilities/toast.test.ts
  src/utilities/toast.ts
Labels: feature

#324 Support conditional rendering of tooltips
  src/components/timeline/TimelineLockControl.svelte
  src/utilities/tooltip.ts
Labels: refactor

#334 Upgrade deps to latest
  package-lock.json
  package.json
  src/components/scheduling/goals/SchedulingGoal.svelte
  src/components/ui/DataGrid/DataGrid.svelte
  vite.config.js
Labels: build

#328 Delete activity with keyboard `Delete`
  src/components/activity/ActivityTable.svelte
  src/components/timeline/LayerActivity.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelinePanel.svelte
  src/components/ui/DataGrid/BulkActionDataGrid.svelte
  src/components/ui/DataGrid/DataGrid.svelte
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
  src/utilities/keyboardEvents.test.ts
  src/utilities/keyboardEvents.ts
Labels: feature

#340 Replace keyboard save checks to use util function
  src/components/constraints/ConstraintForm.svelte
  src/components/expansion/ExpansionRuleForm.svelte
  src/components/scheduling/conditions/SchedulingConditionForm.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/sequencing/SequenceForm.svelte
  src/routes/plans/[id]/+page.svelte
Labels: refactor

#342 Context menu typography tweaks
  src/components/context-menu/ContextMenuHeader.svelte
  src/components/context-menu/ContextMenuItem.svelte
Labels: refactor

#348 Add ellipsis to list item
  src/components/ui/ListItem.svelte
Labels: bug, fix

#351 Replace simulation subscriptions with queries
  src/routes/plans/[id]/+page.svelte
  src/routes/plans/[id]/+page.ts
  src/stores/simulation.ts
  src/types/simulation.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/resources.test.ts
  src/utilities/resources.ts
Labels: bug, fix

#341 Allow unlocking plan while in the process of dragging activity
  src/components/timeline/LayerActivity.svelte
Labels: refactor

#355 Update expansion rule to latest format in e2e test
  e2e-tests/fixtures/ExpansionRules.ts
Labels: test

#315 Timeline layer editing
  e2e-tests/tests/plan-merge.test.ts
  e2e-tests/tests/timeline-view-editing.test.ts
  src/components/activity/ActivityTableMenu.svelte
  src/components/constraints/ConstraintEditor.svelte
  src/components/constraints/ConstraintForm.svelte
  src/components/constraints/Constraints.svelte
  src/components/expansion/ExpansionLogicEditor.svelte
  src/components/expansion/ExpansionRuleForm.svelte
  src/components/expansion/ExpansionRules.svelte
  src/components/expansion/ExpansionSetForm.svelte
  src/components/expansion/ExpansionSets.svelte
  src/components/form/ColorPicker.svelte
  src/components/form/ColorSchemePicker.svelte
  src/components/menus/Menu.svelte
  src/components/plan/PlanMergeReview.svelte
  src/components/scheduling/SchedulingEditor.svelte
  src/components/scheduling/conditions/SchedulingConditionEditor.svelte
  src/components/scheduling/conditions/SchedulingConditionForm.svelte
  src/components/scheduling/conditions/SchedulingConditions.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/scheduling/goals/SchedulingGoals.svelte
  src/components/sequencing/SequenceEditor.svelte
  src/components/sequencing/SequenceForm.svelte
  src/components/sequencing/Sequences.svelte
  src/components/timeline/LayerActivity.svelte
  src/components/timeline/LayerLine.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/TimelineCursors.svelte
  src/components/timeline/form/TimelineEditorLayerFilter.svelte
  src/components/timeline/form/TimelineEditorLayerSelectedFilters.svelte
  src/components/timeline/form/TimelineEditorLayerSettings.svelte
  src/components/timeline/form/TimelineEditorPanel.svelte
  src/components/ui/Chip.svelte
  src/components/ui/SectionTitle.svelte
  src/css/stellar.css
  src/routes/dictionaries/+page.svelte
  src/routes/models/+page.svelte
  src/routes/plans/+page.svelte
  src/routes/plans/[id]/+page.svelte
  src/routes/plans/[id]/+page.ts
  src/schemas/ui-view-schema.json
  src/stores/activities.ts
  src/stores/resource.ts
  src/stores/simulation.ts
  src/stores/views.ts
  src/types/timeline.ts
  src/utilities/effects.ts
  src/utilities/timeline.test.ts
  src/utilities/timeline.ts
  src/utilities/view.ts
Labels: feature

#356 Remove deprecated Timeline Form
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan.test.ts
  src/components/menus/GridMenu.svelte
  src/components/timeline/form/TimelineFormPanel.svelte
  src/routes/plans/[id]/+page.svelte
Labels: refactor

#354 Pre-populate end time with start time during plan creation
  e2e-tests/tests/plans.test.ts
  src/routes/plans/+page.svelte
Labels: feature

#359 Release Version 1.0.2
  package-lock.json
  package.json
Labels: release
