Repository NASA-AMMOS/aerie-ui, pull requests merged in 2023-02, with the labels that each got.

#365 Add and use MenuHeader component
  src/components/activity/ActivityTableMenu.svelte
  src/components/form/ColorSchemePicker.svelte
  src/components/menus/MenuHeader.svelte
  src/components/timeline/form/TimelineEditorLayerFilter.svelte
  src/components/timeline/form/TimelineEditorLayerSettings.svelte
Labels: refactor

#370 Update doc link to new doc site
  src/components/menus/AppMenu.svelte
Labels: refactor

#378 Fix e2e test for opening GraphQL console
  e2e-tests/fixtures/AppNav.ts
  e2e-tests/tests/app-nav.test.ts
  src/components/menus/AppMenu.svelte
Labels: test

#384 Draw ParameterBaseRightAdornments on Struct Params
  src/components/parameters/ParameterRecStruct.svelte
Labels: bug, fix

#338 Add form for anchoring directives to other directives
  src/components/activity/ActivityAnchorForm.svelte
  src/components/activity/ActivityAnchorForm.svelte.test.ts
  src/components/activity/ActivityDecomposition.svelte.test.ts
  src/components/activity/ActivityForm.svelte
  src/components/activity/ActivityTablePanel.svelte
  src/components/plan/PlanMergeReview.svelte
  src/routes/plans/[id]/+page.svelte
  src/stores/activities.ts
  src/stores/errors.ts
  src/types/activity.ts
  src/types/errors.ts
  src/types/plan.ts
  src/types/time.ts
  src/utilities/activities.test.ts
  src/utilities/activities.ts
  src/utilities/effects.ts
  src/utilities/errors.ts
  src/utilities/gql.ts
  src/utilities/time.test.ts
  src/utilities/time.ts
Labels: feature

#371 Navbar status and action menus
  e2e-tests/fixtures/Plan.ts
  e2e-tests/fixtures/SchedulingGoals.ts
  e2e-tests/tests/plan-merge.test.ts
  e2e-tests/tests/plan.test.ts
  e2e-tests/tests/scheduling.test.ts
  src/components/app/Nav.svelte
  src/components/expansion/ExpansionPanel.svelte
  src/components/menus/ViewMenu.svelte
  src/components/plan/PlanNavButton.svelte
  src/components/scheduling/SchedulingGoalsPanel.svelte
  src/components/simulation/SimulationPanel.svelte
  src/components/ui/PanelHeaderActionButton.svelte
  src/components/ui/StatusBadge.svelte
  src/routes/plans/[id]/+page.svelte
  src/stores/expansion.ts
  src/stores/scheduling.ts
  src/stores/simulation.ts
  src/types/scheduling.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/status.ts
Labels: feature

#388 Account for null target activity in non-conflicting activity in plan merge
  src/components/plan/PlanMergeReview.svelte
  src/types/plan.ts
Labels: bug, fix

#389 Release v1.1.0
  package-lock.json
  package.json
Labels: release

#383 Update the UI with the changes to Sequences eDSL
  src/components/sequencing/SequenceForm.svelte
  src/utilities/gql.ts
Labels: refactor, sequencing

#393 Revalidate when selected activity changes
  src/components/activity/ActivityAnchorForm.svelte
Labels: fix

#394 Fix error with nulls in target/source for conflicting and non-conflicting activities
  src/components/plan/PlanMergeReview.svelte
  src/components/plan/PlanMergeReview.test.ts
  src/types/plan.ts
  src/utilities/activities.ts
Labels: bug, fix

#387 Refactor view grid to be simpler
  src/components/activity/ActivityFormPanel.svelte
  src/components/activity/ActivityTablePanel.svelte
  src/components/activity/ActivityTypesPanel.svelte
  src/components/constraints/ConstraintViolationsPanel.svelte
  src/components/constraints/ConstraintsPanel.svelte
  src/components/expansion/ExpansionPanel.svelte
  src/components/menus/GridMenu.svelte
  src/components/scheduling/SchedulingConditionsPanel.svelte
  src/components/scheduling/SchedulingGoalsPanel.svelte
  src/components/simulation/SimulationPanel.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelinePanel.svelte
  src/components/timeline/form/TimelineEditorPanel.svelte
  src/components/ui/IFramePanel.svelte
  src/components/ui/PlanGrid.svelte
  src/components/ui/SplitGrid.svelte
  src/components/view/ViewEditorPanel.svelte
  src/routes/plans/[id]/+page.svelte
  src/schemas/ui-view-schema.json
  src/stores/views.ts
  src/types/grid.ts
  src/types/view.ts
  src/utilities/grid.ts
  src/utilities/view.ts
Labels: breaking change, refactor

#401 Toggle view panels via new menu buttons
  package-lock.json
  package.json
  src/components/menus/ViewMenu.svelte
  src/components/ui/CssGrid.svelte
  src/components/ui/PlanGrid.svelte
  src/components/ui/ToggleableIcon.svelte
  src/routes/plans/[id]/+page.svelte
  src/stores/views.ts
  src/types/view.ts
  src/utilities/view.ts
  svelte.config.js
Labels: feature

#402 Add check for existing selected nodes when auto scrolling table
  src/components/ui/DataGrid/DataGrid.svelte
Labels: bug, fix

#410 Upgrade deps to latest
  package-lock.json
  package.json
Labels: build, fix

#411 Make sure Monaco Editor setValue is not null
  src/components/ui/MonacoEditor.svelte
Labels: bug, fix

#391 Replace View Editor with View Upload Modal
  e2e-tests/data/invalid-view.json
  e2e-tests/data/valid-view.json
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan.test.ts
  src/components/menus/GridMenu.svelte
  src/components/menus/ViewMenu.svelte
  src/components/modals/UploadViewModal.svelte
  src/components/ui/PlanGrid.svelte
  src/components/view/ViewEditorPanel.svelte
  src/routes/plans/[id]/+page.svelte
  src/types/view.ts
  src/utilities/effects.ts
  src/utilities/modal.ts
Labels: refactor

#403 Support plans without scheduling specs
  src/components/scheduling/conditions/SchedulingConditionForm.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte.test.ts
  src/routes/plans/[id]/+page.ts
  src/utilities/effects.ts
Labels: fix

#412 Prevent plan creation invalid date
  src/components/ui/DatePicker/DatePicker.svelte
  src/routes/plans/+page.svelte
Labels: bug, fix
