Repository NASA-AMMOS/aerie-ui, pull requests merged in 2023-10, with the labels that each got.

#921 Properly align icons in plan navbar buttons
  src/components/plan/PlanNavButton.svelte
Labels: fix

#929 Add ability to create a new snapshot before restoring a snapshot
  src/components/modals/RestorePlanSnapshotModal.svelte
  src/routes/plans/[id]/+page.svelte
  src/utilities/effects.ts
  src/utilities/modal.ts
Labels: feature

#909 Activity Changelog UI
  e2e-tests/tests/plan-activities.test.ts
  package-lock.json
  package.json
  src/components/activity/ActivityAnchorForm.svelte
  src/components/activity/ActivityDirectiveChangelog.svelte
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/activity/ActivityFormPanel.svelte
  src/types/activity.ts
  src/utilities/activities.test.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: feature

#920 Added support for showing and accessing custom helpers
  src/components/menus/ExtensionMenu.svelte
  src/routes/extensions/+server.ts
  src/routes/plans/[id]/+page.svelte
  src/routes/plans/[id]/+page.ts
  src/types/extension.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/requests.ts
Labels: feature

#945 Release v1.14.0
  package-lock.json
  package.json
Labels: release

#950 Utilize svelte `base` for importing files during runtime to allow for proxied deployment configurations
  src/components/ui/MonacoEditor.svelte
Labels: fix

#960 Zooming improvements
  src/components/form/DatePickerField.svelte
  src/components/timeline/LayerLine.svelte
  src/components/timeline/LayerXRange.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelineContextMenu.svelte
  src/components/timeline/TimelineViewControls.svelte
  src/enums/time.ts
Labels: feature

#969 include effective arguments in preset
  src/components/activity/ActivityDirectiveForm.svelte
  src/utilities/effects.ts
Labels: fix
