Repository NASA-AMMOS/aerie-ui, pull requests merged in 2023-08, with the labels that each got.

#799 TS AST - Pass by Position Argument Validation
  src/workers/customCodes.ts
  src/workers/diagnostics/commandArgumentsDiagnostics.ts
  src/workers/workerHelpers.ts
Labels: feature, sequencing

#816 Specify type="button" in DatePickerActionButton
  src/components/ui/DatePicker/DatePickerActionButton.svelte
Labels: fix

#813 Fix directives getting removed from UI when not actually being deleted
  src/utilities/effects.ts
Labels: fix

#818 Supply optional expansion set name during set creation
  src/components/expansion/ExpansionSetForm.svelte
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: feature

#810 Global tag management
  package-lock.json
  package.json
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/activity/ActivityDirectivesTablePanel.svelte
  src/components/constraints/ConstraintForm.svelte
  src/components/expansion/ExpansionRuleForm.svelte
  src/components/form/ColorPresetsPicker.svelte
  src/components/menus/AppMenu.svelte
  src/components/modals/ConfirmModal.svelte
  src/components/plan/PlanForm.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/ui/Chip.svelte
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
  src/components/ui/Tags/TagsInput.svelte
  src/components/ui/Tags/TagsInput.svelte.test.ts
  src/routes/plans/+page.svelte
  src/routes/tags/+page.svelte
  src/routes/tags/+page.ts
  src/stores/tags.ts
  src/types/tags.ts
  src/utilities/color.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
  src/utilities/validators.ts
Labels: feature

#819 Display version in model selector in plan form
  e2e-tests/tests/plans.test.ts
  src/routes/plans/+page.svelte
Labels: feature

#817 More specific deletion messages
  src/components/constraints/ConstraintListItem.svelte
  src/components/constraints/Constraints.svelte
  src/components/expansion/ExpansionRules.svelte
  src/components/expansion/ExpansionSets.svelte
  src/components/modals/SavedViewsModal.svelte
  src/components/scheduling/Scheduling.svelte
  src/components/scheduling/conditions/SchedulingCondition.svelte
  src/components/scheduling/goals/SchedulingGoal.svelte
  src/components/sequencing/Sequences.svelte
  src/routes/plans/+page.svelte
  src/utilities/effects.ts
Labels: feature

#828 Nullable owner type and tag editor fixes
  src/components/expansion/ExpansionRuleForm.svelte
  src/components/sequencing/SequenceForm.svelte
  src/components/ui/Chip.svelte
  src/routes/tags/+page.svelte
  src/types/app.ts
  src/types/constraint.ts
  src/types/expansion.ts
  src/types/model.ts
  src/types/plan.ts
  src/types/sequencing.ts
  src/types/tags.ts
  src/types/view.ts
Labels: fix

#820 Added Balanced Time Checking to Custom Worker
  src/workers/customCodes.ts
  src/workers/diagnostics/timeDiagnostics.ts
  src/workers/workerHelpers.ts
Labels: feature, sequencing

#837 Handle "silent" errors
  src/stores/__mocks__/plan.mock.ts
  src/utilities/effects.test.ts
  src/utilities/effects.ts
  src/utilities/requests.ts
Labels: fix

#838 Add back removed filter type for layer
  src/components/timeline/form/TimelineEditorPanel.svelte
Labels: fix

#839 Expansion Editor: Fix the custom worker not starting up correctly
  src/components/expansion/ExpansionLogicEditor.svelte
Labels: bug, sequencing

#842 Fix UI permissions
  src/components/constraints/ConstraintForm.svelte
  src/components/constraints/Constraints.svelte
  src/components/constraints/ConstraintsPanel.svelte
  src/components/context-menu/ContextMenuItem.svelte
  src/components/expansion/ExpansionRuleForm.svelte
  src/components/expansion/ExpansionRules.svelte
  src/components/expansion/ExpansionSetForm.svelte
  src/components/menus/MenuItem.svelte
  src/components/parameters/ValueSourceBadge.svelte
  src/components/plan/PlanMergeReview.svelte
  src/components/plan/PlanNavButton.svelte
  src/components/scheduling/conditions/SchedulingConditions.svelte
  src/components/scheduling/goals/SchedulingGoals.svelte
  src/components/sequencing/SequenceForm.svelte
  src/components/sequencing/Sequences.svelte
  src/components/timeline/LayerActivity.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelineContextMenu.svelte
  src/components/timeline/TimelinePanel.svelte
  src/components/ui/PanelHeaderActionButton.svelte
  src/routes/tags/+page.svelte
  src/utilities/permissionHandler.ts
Labels: refactor

#849 Add resource name to plot tooltips
  src/components/timeline/Tooltip.svelte
Labels: feature

#848 Remove reset text from value source badge if disabled
  src/components/parameters/ParameterBaseBoolean.svelte
  src/components/parameters/ParameterBaseDuration.svelte
  src/components/parameters/ParameterBaseNumber.svelte
  src/components/parameters/ParameterBasePath.svelte
  src/components/parameters/ParameterBaseRightAdornments.svelte
  src/components/parameters/ParameterBaseString.svelte
  src/components/parameters/ParameterBaseVariant.svelte
  src/components/parameters/ParameterRecSeries.svelte
  src/components/parameters/ParameterRecStruct.svelte
  src/components/parameters/ValueSourceBadge.svelte
Labels: fix

#850 Fix miscalculated parameter padding
  src/components/Collapse.svelte
Labels: fix

#852 Prevent non-activities from being dragged onto an activity layer
  src/components/timeline/Row.svelte
Labels: fix

#859 Update plan snapshot queries to latest API
  src/components/modals/PlanMergeRequestsModal.svelte
  src/components/plan/PlanMergeReview.svelte
  src/components/plan/PlanMergeReview.test.ts
  src/types/plan.ts
  src/utilities/gql.ts
Labels: refactor

#858 Release v1.12.0
  package-lock.json
  package.json
Labels: release

#869 Fix setting vertical guide color from timeline editor
  src/components/timeline/form/TimelineEditorPanel.svelte
Labels: fix

#871 Show Success Toast when Constraints Successfully Update
  src/utilities/effects.ts
Labels: fix

#873 Fix tag filtering in tables
  src/components/activity/ActivityDirectivesTablePanel.svelte
  src/components/constraints/Constraints.svelte
  src/components/expansion/ExpansionRules.svelte
  src/components/scheduling/goals/SchedulingGoals.svelte
  src/components/ui/DataGrid/DataGridTags.ts
  src/routes/plans/+page.svelte
Labels: fix

#874 Catch and print 'parse-failed' errors nicely
  src/utilities/requests.ts
Labels: fix

#847 Update Constraint Violations to Use New Schema
  src/components/constraints/ConstraintListItem.svelte
  src/components/constraints/ConstraintsPanel.svelte
  src/components/timeline/ConstraintViolations.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelineHistogram.svelte
  src/components/timeline/TimelinePanel.svelte
  src/components/timeline/Tooltip.svelte
  src/components/timeline/XAxis.svelte
  src/routes/plans/[id]/+page.svelte
  src/stores/constraints.ts
  src/types/constraint.ts
  src/types/timeline.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
Labels: refactor, constraints
