Repository NASA-AMMOS/aerie-ui, pull requests merged in 2024-08, with the labels that each got.

#1407 [Bug] Boolean args not supported for arguments
  src/components/sequencing/form/ArgEditor.svelte
  src/components/sequencing/form/BooleanEditor.svelte
  src/utilities/codemirror/codemirror-utils.ts
  src/utilities/codemirror/sequence.grammar
  src/utilities/sequence-editor/from-seq-json.test.ts
  src/utilities/sequence-editor/from-seq-json.ts
  src/utilities/sequence-editor/sequence-linter.ts
  src/utilities/sequence-editor/to-seq-json.test.ts
  src/utilities/sequence-editor/to-seq-json.ts
Labels: bug, sequencing

#1421 Release v2.17.0
  package-lock.json
  package.json
Labels: release

#1422 Small plan export improvements
  src/components/plan/PlanForm.svelte
  src/components/ui/CancellableProgressRadial.svelte
  src/components/ui/DataGrid/DataGrid.svelte
  src/components/ui/DataGrid/DataGridActions.svelte
  src/routes/plans/+page.svelte
Labels: refactor, fix

#1425 Sequence Editor Auto-indent, Ground support
  src/components/sequencing/SequenceEditor.svelte
  src/utilities/codemirror/custom-folder.test.ts
  src/utilities/codemirror/custom-folder.ts
  src/utilities/codemirror/index.ts
  src/utilities/sequence-editor/sequence-autoindent.ts
  src/utilities/sequence-editor/sequence-completion.ts
Labels: feature, sequencing

#1427 Change model ids from type `ID!` to `Int!`
  src/utilities/gql.ts
Labels: refactor

#1440 Release v2.18.0
  package-lock.json
  package.json
Labels: release
