Repository NASA-AMMOS/aerie-ui, pull requests merged in 2024-10, with the labels that each got.

#1475 Fixes dependency vulnerabilities
  package-lock.json
  package.json
Labels: maintenance

#1488 Release v2.21.0
  package-lock.json
  package.json
Labels: release

#1489 Allow parsing month of October
  src/utilities/time.test.ts
  src/utilities/time.ts
Labels: fix

#1511 Double click plan row to open plan
  src/routes/plans/+page.svelte
Labels: feature

#1494 Local and Parameter Blocks
  src/utilities/codemirror/custom-folder.test.ts
  src/utilities/codemirror/custom-folder.ts
  src/utilities/codemirror/index.ts
  src/utilities/codemirror/sequence.grammar
  src/utilities/sequence-editor/from-seq-json.test.ts
  src/utilities/sequence-editor/from-seq-json.ts
  src/utilities/sequence-editor/grammar.test.ts
  src/utilities/sequence-editor/sequence-completion.ts
  src/utilities/sequence-editor/sequence-linter.ts
  src/utilities/sequence-editor/to-seq-json.test.ts
  src/utilities/sequence-editor/to-seq-json.ts
  src/utilities/sequence-editor/token.test.ts
Labels: sequencing

#1518 Release v3.0.0
  package-lock.json
  package.json
Labels: release
