Repository NASA-AMMOS/aerie-ui, pull requests merged in 2024-11, with the labels that each got.

#1528 Fix sequencing page resizing behavior (#1457)
  src/components/sequencing/Sequences.svelte
Labels: fix

#1529 Parameter info icon misaligned in ParameterRecSeries or ParameterRecStruct (#1473)
  src/components/parameters/ParameterRec.svelte
  src/components/parameters/ParameterRecSeries.svelte
  src/components/parameters/ParameterRecStruct.svelte
Labels: fix

#1538 Add "scroll to activity" to activity directive table context menu (#1433)
  src/components/activity/ActivityDirectivesTable.svelte
  src/components/activity/ActivityDirectivesTablePanel.svelte
  src/components/timeline/TimelineViewControls.svelte
  src/components/ui/DataGrid/BulkActionDataGrid.svelte
  src/utilities/timeline.test.ts
  src/utilities/timeline.ts
Labels: feature

#1559 Release v3.1.1
  package-lock.json
  package.json
Labels: release

#1563 Release v3.0.1
  package-lock.json
  package.json
Labels: release

#1539 Library Sequences from Workspace
  src/components/expansion/ExpansionRuns.svelte
  src/components/sequencing/SequenceEditor.svelte
  src/components/sequencing/SequenceForm.svelte
  src/components/sequencing/Sequences.svelte
  src/types/sequencing.ts
  src/utilities/codemirror/codemirror-utils.test.ts
  src/utilities/codemirror/codemirror-utils.ts
  src/utilities/codemirror/seq-n-tree-utils.ts
  src/utilities/sequence-editor/extension-points.ts
  src/utilities/sequence-editor/sequence-completion.ts
  src/utilities/sequence-editor/sequence-linter.ts
  src/utilities/sequence-editor/to-seq-json.test.ts
  src/utilities/sequence-editor/to-seq-json.ts
Labels: sequencing
