Repository NASA-AMMOS/aerie-ui, pull requests merged in 2024-09, with the labels that each got.

#1418 MVP Procedural Scheduling UI
  .vscode/settings.json
  src/components/modals/ManagePlanSchedulingGoalsModal.svelte
  src/components/scheduling/SchedulingGoalsPanel.svelte
  src/components/scheduling/goals/SchedulingGoal.svelte
  src/types/scheduling.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: DON'T MERGE

#1444 Scheduling jar upload
  e2e-tests/data/example-procedure.jar
  src/components/constraints/ConstraintForm.svelte
  src/components/scheduling/conditions/SchedulingConditionForm.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/ui/Association/AssociationForm.svelte
  src/components/ui/Association/DefinitionEditor.svelte
  src/constants/scheduling.ts
  src/enums/association.ts
  src/routes/constraints/edit/[id]/+page.svelte
  src/routes/scheduling/conditions/edit/[id]/+page.svelte
  src/routes/scheduling/goals/edit/[id]/+page.svelte
  src/types/metadata.ts
  src/types/scheduling.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: DON'T MERGE

#1456 Release v2.19.0
  package-lock.json
  package.json
Labels: release

#1443 Sequence Editor Ground epoch time tag
  src/utilities/codemirror/custom-folder.test.ts
  src/utilities/codemirror/index.ts
  src/utilities/codemirror/sequence.grammar
  src/utilities/sequence-editor/from-seq-json.test.ts
  src/utilities/sequence-editor/from-seq-json.ts
  src/utilities/sequence-editor/grammar.test.ts
  src/utilities/sequence-editor/sequence-completion.ts
  src/utilities/sequence-editor/sequence-linter.ts
  src/utilities/sequence-editor/to-seq-json.test.ts
  src/utilities/sequence-editor/to-seq-json.ts
  src/utilities/sequence-editor/token.test.ts
Labels: sequencing

#1468 Update dependencies
  e2e-tests/fixtures/Constraints.ts
  e2e-tests/fixtures/Dictionaries.ts
  e2e-tests/fixtures/ExpansionRules.ts
  e2e-tests/fixtures/Model.ts
  e2e-tests/fixtures/Models.ts
  e2e-tests/fixtures/Parcels.ts
  e2e-tests/fixtures/Plans.ts
  e2e-tests/fixtures/SchedulingConditions.ts
  e2e-tests/fixtures/SchedulingGoals.ts
  e2e-tests/fixtures/Sequence.ts
  e2e-tests/fixtures/View.ts
  package-lock.json
  package.json
  src/components/ui/DataGrid/DataGrid.svelte
  src/css/ag-grid-stellar.css
Labels: refactor

#1469 Release v2.20.0
  package-lock.json
  package.json
Labels: release
