Repository NASA-AMMOS/aerie-ui, pull requests merged in 2024-03, with the labels that each got.

#1143 Release v2.5.0
  package-lock.json
  package.json
Labels: release

#1144 Change `scheduling_specifications` to `scheduling_specification`
  src/components/plan/PlanMergeReview.test.ts
  src/components/scheduling/Scheduling.svelte
  src/components/scheduling/conditions/SchedulingConditionForm.svelte
  src/components/scheduling/conditions/SchedulingConditions.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte.test.ts
  src/components/scheduling/goals/SchedulingGoals.svelte
  src/routes/plans/[id]/+page.ts
  src/stores/scheduling.ts
  src/types/plan.ts
  src/utilities/gql.ts
Labels: refactor

#1146 Activity Layer Context Menu Fix
  src/components/timeline/LayerActivity.svelte
Labels: fix

#1166 Fix editing of plan tags
  src/components/plan/PlanForm.svelte
  src/utilities/permissions.ts
Labels: fix

#1149 Shared scheduling MVP
  e2e-tests/fixtures/Constraints.ts
  e2e-tests/fixtures/Plan.ts
  e2e-tests/fixtures/SchedulingConditions.ts
  e2e-tests/fixtures/SchedulingGoals.ts
  e2e-tests/tests/scheduling.test.ts
  src/components/constraints/ConstraintForm.svelte
  src/components/constraints/Constraints.svelte
  src/components/modals/ManagePlanSchedulingConditionsModal.svelte
  src/components/modals/ManagePlanSchedulingGoalsModal.svelte
  src/components/scheduling/Scheduling.svelte
  src/components/scheduling/SchedulingConditionsPanel.svelte
  src/components/scheduling/SchedulingEditor.svelte
  src/components/scheduling/SchedulingGoalsPanel.svelte
  src/components/scheduling/conditions/SchedulingCondition.svelte
  src/components/scheduling/conditions/SchedulingConditionEditor.svelte
  src/components/scheduling/conditions/SchedulingConditionForm.svelte
  src/components/scheduling/conditions/SchedulingConditions.svelte
  src/components/scheduling/goals/SchedulingGoal.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte.test.ts
  src/components/scheduling/goals/SchedulingGoals.svelte
  src/components/sequencing/SequenceEditor.svelte
  src/components/ui/Association/AssociationForm.svelte
  src/components/ui/Association/DefinitionEditor.svelte
  src/components/ui/MonacoEditor.svelte
  src/routes/constraints/edit/[id]/+page.svelte
  src/routes/constraints/new/+page.svelte
  src/routes/plans/[id]/+page.svelte
  src/routes/plans/[id]/+page.ts
  src/routes/scheduling/+page.svelte
  src/routes/scheduling/+page.ts
  src/routes/scheduling/conditions/edit/[id]/+page.svelte
  src/routes/scheduling/conditions/edit/[id]/+page.ts
  src/routes/scheduling/conditions/new/+page.svelte
  src/routes/scheduling/conditions/new/+page.ts
  src/routes/scheduling/goals/edit/[id]/+page.svelte
  src/routes/scheduling/goals/edit/[id]/+page.ts
  src/routes/scheduling/goals/new/+page.svelte
  src/routes/scheduling/goals/new/+page.ts
  src/stores/constraints.ts
  src/stores/scheduling.ts
  src/types/constraint.ts
  src/types/metadata.ts
  src/types/plan.ts
  src/types/scheduling.ts
  src/types/tags.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/modal.ts
  src/utilities/permissions.ts
  src/utilities/scheduling.ts
Labels: feature

#1172 Release v2.6.0
  package-lock.json
  package.json
Labels: release

#1185 Default plans table sorting to descending IDs
  src/routes/plans/+page.svelte
Labels: fix

#1184 Update contribution docs to be more explicit about rebasing and testing
  docs/CONTRIBUTING.md
Labels: documentation

#1189 Add extension recommendations for VSCode
  .vscode/extensions.json
Labels: refactor

#1188 refactor: use mouseup instead of click on menu items
  src/components/menus/MenuItem.svelte
Labels: refactor

#1193 refactor: use mouseup instead of click on context-menu items
  src/components/context-menu/ContextMenuItem.svelte
Labels: refactor

#1186 Add a string comparison on the output of the `derived` store
  src/components/ui/Association/AssociationForm.svelte
  src/stores/derivedDeeply.ts
  src/stores/scheduling.ts
Labels: refactor

#1196 Release v2.6.1
  package-lock.json
  package.json
Labels: release

#1194 Fix ability for admin to edit tags on associations that they do not own
  src/components/constraints/ConstraintForm.svelte
  src/components/scheduling/SchedulingGoalsPanel.svelte
  src/components/scheduling/conditions/SchedulingConditionForm.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/ui/Association/AssociationForm.svelte
  src/utilities/effects.ts
  src/utilities/permissions.ts
Labels: fix

#1187 Tooltip delay
  src/components/plan/PlanNavButton.svelte
  src/utilities/permissionHandler.ts
  src/utilities/tooltip.ts
Labels: refactor

#1197 Use fake timers in test to fix potential issue with `window` references post test
  src/components/ui/DataGrid/DataGrid.test.ts
Labels: refactor
