Repository NASA-AMMOS/aerie-ui, pull requests merged in 2024-02, with the labels that each got.

#1053 Add SSO support
  .env
  .gitignore
  docs/ENVIRONMENT.md
  package-lock.json
  package.json
  src/hooks.server.ts
  src/routes/+layout.server.ts
  src/routes/auth/logout/+server.ts
  src/routes/login/+page.ts
  src/stores/subscribable.ts
  src/types/auth.ts
  src/utilities/login.test.ts
  src/utilities/login.ts
  src/utilities/requests.ts
  vite.config.js
Labels: feature, clipper, auth

#1115 Set expiration time in the past for `activeRole` cookie
  src/routes/auth/logout/+server.ts
Labels: fix, auth

#1116 Release v2.3.0
  package-lock.json
  package.json
Labels: release

#1127 Release v2.2.2
  package-lock.json
  package.json
Labels: release

#1049 Line layer decimation, interpolation, snapping, and tooltip improvements
  package-lock.json
  package.json
  src/components/timeline/LayerLine.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelineInteractionModeControl.svelte
  src/components/timeline/TimelineLockControl.svelte
  src/components/timeline/TimelinePanel.svelte
  src/components/timeline/TimelineViewControls.svelte
  src/components/timeline/TimelineViewDirectiveControls.svelte
  src/components/timeline/Tooltip.svelte
  src/components/ui/ToggleableIconButton.svelte
  src/css/tooltip.css
  src/types/timeline.ts
  src/utilities/timeline.ts
Labels: performance, timeline

#1129 Fixed not being able to delete expansion sets
  src/utilities/effects.ts
Labels: bug

#1132 Release v2.4.0
  package-lock.json
  package.json
Labels: release

#1131 Overwrite `activeRole` cookie when it's not contained in allowed roles list
  src/hooks.server.ts
Labels: fix
