Repository NASA-AMMOS/aerie-ui, pull requests merged in 2024-07, with the labels that each got.

#1357 Add plan JSON export
  src/components/plan/PlanForm.svelte
  src/components/plan/PlanMergeReview.test.ts
  src/components/plan/PlanMetadataPanel.svelte
  src/types/plan.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/plan.test.ts
  src/utilities/plan.ts
Labels: feature

#1377 Release v2.15.0
  package-lock.json
  package.json
Labels: release

#1383 Revert "Feat/seqgen grammar v2"
  src/app.d.ts
  src/components/sequencing/form/SelectedCommand.svelte
  src/utilities/codemirror/codemirror-utils.ts
  src/utilities/codemirror/index.ts
  src/utilities/codemirror/sequence.grammar
  src/utilities/new-sequence-editor/from-seq-json.test.ts
  src/utilities/new-sequence-editor/from-seq-json.ts
  src/utilities/new-sequence-editor/grammar.test.ts
  src/utilities/new-sequence-editor/sequencer-grammar-constants.ts
  src/utilities/new-sequence-editor/to-seq-json.test.ts
  src/utilities/new-sequence-editor/to-seq-json.ts
  src/utilities/new-sequence-editor/token.test.ts
  src/utilities/new-sequence-editor/tree-utils.ts
Labels: refactor

#1387 seqgen grammar changes ported to updated mission independent code
  e2e-tests/fixtures/Sequence.ts
  src/app.d.ts
  src/components/sequencing/form/SelectedCommand.svelte
  src/constants/seq-n-grammar-constants.ts
  src/stores/sequence-adaptation.ts
  src/utilities/codemirror/codemirror-utils.ts
  src/utilities/codemirror/index.ts
  src/utilities/codemirror/seq-n-tree-utils.ts
  src/utilities/codemirror/sequence.grammar
  src/utilities/sequence-editor/from-seq-json.test.ts
  src/utilities/sequence-editor/from-seq-json.ts
  src/utilities/sequence-editor/grammar.test.ts
  src/utilities/sequence-editor/sequence-linter.ts
  src/utilities/sequence-editor/sequence-tooltip.ts
  src/utilities/sequence-editor/sequencer-grammar-constants.ts
  src/utilities/sequence-editor/to-seq-json.test.ts
  src/utilities/sequence-editor/to-seq-json.ts
  src/utilities/sequence-editor/token.test.ts
  src/utilities/sequence-editor/tree-utils.ts
Labels: sequencing

#1400 Release v2.16.0
  package-lock.json
  package.json
Labels: release

#1389 Added better linting support inside of the sequence adaptation
  src/app.d.ts
  src/stores/sequence-adaptation.ts
  src/types/sequencing.ts
  src/utilities/sequence-editor/seq-json-linter.ts
  src/utilities/sequence-editor/sequence-linter.ts
Labels: sequencing

#1404 Release v2.11.2
  package-lock.json
  package.json
Labels: release

#1405 Release v2.11.2
  package.json
Labels: release

#1406 Release v2.11.2
  package.json
Labels: release
