Repository NASA-AMMOS/aerie-ui, pull requests merged in 2024-05, with the labels that each got.

#1228 Reduce flakiness of plan-merge test
  e2e-tests/tests/plan-merge.test.ts
Labels: test

#1221 Add feature for defining model specifications
  e2e-tests/fixtures/Constraints.ts
  e2e-tests/fixtures/Model.ts
  e2e-tests/fixtures/Models.ts
  e2e-tests/fixtures/SchedulingConditions.ts
  e2e-tests/fixtures/SchedulingGoals.ts
  e2e-tests/tests/constraints.test.ts
  e2e-tests/tests/model.test.ts
  e2e-tests/tests/models.test.ts
  e2e-tests/tests/plan.test.ts
  e2e-tests/tests/plans.test.ts
  src/components/console/Console.svelte
  src/components/constraints/ConstraintListItem.svelte
  src/components/constraints/Constraints.svelte
  src/components/constraints/ConstraintsPanel.svelte
  src/components/modals/ManagePlanConstraintsModal.svelte
  src/components/modals/ManagePlanSchedulingConditionsModal.svelte
  src/components/modals/ManagePlanSchedulingGoalsModal.svelte
  src/components/model/ModelAssociations.svelte
  src/components/model/ModelAssociationsListItem.svelte
  src/components/model/ModelForm.svelte
  src/components/model/ModelSpecification.svelte
  src/components/model/Models.svelte
  src/components/plan/PlanMergeReview.test.ts
  src/components/scheduling/Scheduling.svelte
  src/components/scheduling/conditions/SchedulingCondition.svelte
  src/components/scheduling/conditions/SchedulingConditions.svelte
  src/components/scheduling/goals/SchedulingGoal.svelte
  src/components/scheduling/goals/SchedulingGoals.svelte
  src/components/ui/Association/AssociationForm.svelte
  src/components/ui/RadioButtons/RadioButton.svelte
  src/components/ui/RadioButtons/RadioButtons.svelte
  src/css/stellar.css
  src/routes/constraints/edit/[id]/+page.svelte
  src/routes/models/+layout.svelte
  src/routes/models/+page.svelte
  src/routes/models/[id]/+page.svelte
  src/routes/models/[id]/+page.ts
  src/routes/plans/+page.svelte
  src/routes/plans/[id]/+page.svelte
  src/routes/scheduling/conditions/edit/[id]/+page.svelte
  src/routes/scheduling/goals/edit/[id]/+page.svelte
  src/stores/constraints.ts
  src/stores/model.ts
  src/stores/scheduling.ts
  src/types/constraint.ts
  src/types/metadata.ts
  src/types/model.ts
  src/types/scheduling.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: feature

#1243 Mission Model canary cron job
  .github/workflows/canary.yml
  .github/workflows/test.yml
Labels: ci

#1236 Add simulation events table panel
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan-metadata.test.ts
  e2e-tests/tests/plan-simulation-templates.test.ts
  e2e-tests/tests/plan.test.ts
  e2e-tests/tests/scheduling.test.ts
  e2e-tests/tests/simulation.test.ts
  e2e-tests/tests/timeline-view-editing.test.ts
  src/components/menus/GridMenu.svelte
  src/components/simulation/SimulationEventsPanel.svelte
  src/components/simulation/SimulationEventsTable.svelte
  src/components/ui/PlanGrid.svelte
  src/routes/plans/[id]/+page.svelte
  src/schemas/ui-view-schema.json
  src/stores/simulation.ts
  src/stores/views.ts
  src/types/simulation.ts
  src/types/view.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
  src/utilities/simulation.test.ts
  src/utilities/simulation.ts
  src/utilities/view.ts
Labels: feature

#1268 Release v2.6.3
  package-lock.json
  package.json
Labels: release

#1265 Add UserInput component
  src/components/model/ModelForm.svelte
  src/components/ui/Tags/PlanCollaboratorInput.svelte
  src/components/ui/Tags/TagsInput.svelte
  src/components/ui/Tags/UserInput.svelte
  src/components/ui/Tags/UserInputRow.svelte
  src/routes/models/[id]/+page.svelte
  src/types/tags.ts
Labels: feature

#1285 Release v2.10.0
  package-lock.json
  package.json
Labels: release

#1289 Release v2.11.0
  package-lock.json
  package.json
Labels: release

#1302 SeqJSON Import - Symbol arguments and Immediate/Hardware Commands
  src/utilities/new-sequence-editor/from-seq-json.test.ts
  src/utilities/new-sequence-editor/from-seq-json.ts
Labels: bug, sequencing

#1309 Release v2.12.0
  package-lock.json
  package.json
Labels: release
