Repository NASA-AMMOS/aerie-ui, pull requests merged in 2024-01, with the labels that each got.

#1056 Split Resource -> LinePoint Processing Across Multiple Frames
  src/components/timeline/LayerLine.svelte
  src/types/timeline.ts
Labels: performance

#1073 Display username in app menu
  src/components/app/Nav.svelte
  src/components/menus/AppMenu.svelte
Labels: feature

#1070 Handle non-gap null values in line and x-range plots
  src/components/timeline/LayerLine.svelte
  src/components/timeline/LayerXRange.svelte
  src/components/timeline/RowHeader.svelte
  src/types/timeline.ts
Labels: fix

#1085 Upload file before setting activity parameter path
  e2e-tests/tests/plan-activities.test.ts
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/timeline/LayerActivity.svelte
  src/utilities/effects.ts
Labels: fix

#1084 Fix constraint violations display
  src/components/constraints/ConstraintsPanel.svelte
  src/components/timeline/ConstraintViolations.svelte
  src/components/timeline/Row.svelte
  src/components/timeline/Timeline.svelte
  src/components/timeline/TimelineHistogram.svelte
  src/components/timeline/Tooltip.svelte
  src/components/timeline/XAxis.svelte
  src/routes/plans/[id]/+page.svelte
  src/stores/constraints.ts
  src/types/constraint.ts
  src/types/timeline.ts
  src/utilities/effects.ts
Labels: fix

#1091 Release v2.2.1
  package-lock.json
  package.json
Labels: release

#1093 Release v2.2.1
  package-lock.json
  package.json
Labels: release

#1072 Filter scheduling goals and conditions by plan scheduling specification id
  src/components/scheduling/Scheduling.svelte
  src/components/scheduling/conditions/SchedulingConditions.svelte
  src/components/scheduling/goals/SchedulingGoals.svelte
  src/stores/scheduling.ts
  src/types/permissions.ts
  src/types/scheduling.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: fix
