Repository NASA-AMMOS/aerie-ui, pull requests merged in 2024-06, with the labels that each got.

#1315 Allow for Escape Quote in Phoenix Editor
  src/components/sequencing/form/ArgEditor.svelte
  src/components/sequencing/form/ArgTitle.svelte
  src/components/sequencing/form/EnumEditor.svelte
  src/components/sequencing/form/NumEditor.svelte
  src/components/sequencing/form/SelectedCommand.svelte
  src/components/sequencing/form/StringEditor.svelte
  src/components/sequencing/form/utils.ts
  src/utilities/codemirror/codemirror-utils.test.ts
  src/utilities/codemirror/codemirror-utils.ts
  src/utilities/new-sequence-editor/from-seq-json.test.ts
  src/utilities/new-sequence-editor/from-seq-json.ts
  src/utilities/new-sequence-editor/sequence-linter.ts
  src/utilities/new-sequence-editor/sequence-tooltip.ts
  src/utilities/new-sequence-editor/to-seq-json.test.ts
  src/utilities/new-sequence-editor/to-seq-json.ts
Labels: sequencing

#1332 Release v2.13.0
  package-lock.json
  package.json
Labels: release

#1319 Expose model upload errors
  e2e-tests/fixtures/Models.ts
  e2e-tests/fixtures/Plans.ts
  e2e-tests/tests/constraints.test.ts
  e2e-tests/tests/expansion.test.ts
  e2e-tests/tests/model.test.ts
  e2e-tests/tests/models.test.ts
  e2e-tests/tests/plan-activities.test.ts
  e2e-tests/tests/plan-activity-presets.test.ts
  e2e-tests/tests/plan-merge.test.ts
  e2e-tests/tests/plan-metadata.test.ts
  e2e-tests/tests/plan-simulation-templates.test.ts
  e2e-tests/tests/plan.test.ts
  e2e-tests/tests/plans.test.ts
  e2e-tests/tests/scheduling.test.ts
  e2e-tests/tests/simulation.test.ts
  e2e-tests/tests/timeline-view-editing.test.ts
  e2e-tests/tests/view.test.ts
  src/assets/mission-model.svg
  src/components/console/views/GenericErrors.svelte
  src/components/console/views/ModelErrors.svelte
  src/components/console/views/ModelErrors.svelte.test.ts
  src/components/console/views/ModelErrors.test.svelte
  src/components/model/ModelForm.svelte
  src/components/model/ModelId.svelte
  src/components/model/ModelStatusIcon.svelte
  src/components/model/ModelStatusIcon.svelte.test.ts
  src/components/model/ModelStatusRollup.svelte
  src/components/model/ModelStatusRollup.svelte.test.ts
  src/components/model/Models.svelte
  src/components/plan/PlanMergeReview.test.ts
  src/components/plan/PlanModelErrorBar.svelte
  src/components/ui/ActivityErrorsRollup.svelte
  src/components/ui/DataGrid/BulkActionDataGrid.svelte
  src/components/ui/DataGrid/DataGrid.svelte
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
  src/components/ui/ProgressRadial.svelte
  src/routes/models/[id]/+page.svelte
  src/routes/plans/+page.svelte
  src/routes/plans/[id]/+page.svelte
  src/stores/model.ts
  src/types/model.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/model.test.ts
  src/utilities/model.ts
Labels: feature

#1333 Make e2e less flaky (still not 100%)
  .vscode/tasks.json
  e2e-tests/fixtures/Constraints.ts
  e2e-tests/fixtures/Dictionaries.ts
  e2e-tests/fixtures/ExpansionRules.ts
  e2e-tests/fixtures/Model.ts
  e2e-tests/fixtures/Models.ts
  e2e-tests/fixtures/Parcels.ts
  e2e-tests/fixtures/Plan.ts
  e2e-tests/fixtures/Plans.ts
  e2e-tests/fixtures/SchedulingConditions.ts
  e2e-tests/fixtures/SchedulingGoals.ts
  e2e-tests/fixtures/Sequence.ts
  e2e-tests/fixtures/Tags.ts
  e2e-tests/fixtures/User.ts
  e2e-tests/fixtures/View.ts
  e2e-tests/tests/constraints.test.ts
  e2e-tests/tests/expansion.test.ts
  e2e-tests/tests/model.test.ts
  e2e-tests/tests/models.test.ts
  e2e-tests/tests/parcels.test.ts
  e2e-tests/tests/plan-activities.test.ts
  e2e-tests/tests/plan-activity-presets.test.ts
  e2e-tests/tests/plan-merge.test.ts
  e2e-tests/tests/plan-metadata.test.ts
  e2e-tests/tests/plan-simulation-templates.test.ts
  e2e-tests/tests/plan.test.ts
  e2e-tests/tests/plans.test.ts
  e2e-tests/tests/scheduling.test.ts
  e2e-tests/tests/sequence.test.ts
  e2e-tests/tests/simulation.test.ts
  e2e-tests/tests/timeline-view-editing.test.ts
  e2e-tests/tests/view.test.ts
  src/components/plan/PlanForm.svelte
  src/components/scheduling/SchedulingGoalsPanel.svelte
  src/components/ui/Tags/PlanCollaboratorInput.svelte
  src/routes/plans/+page.svelte
  src/stores/form.ts
  src/types/form.ts
Labels: test

#1335 Handle Escaped Quotes in Metadata and Models values
  src/tests/mocks/sequencing/grammar-cases/parse_tree.txt
  src/utilities/codemirror/sequence.grammar
  src/utilities/new-sequence-editor/to-seq-json.test.ts
  src/utilities/new-sequence-editor/to-seq-json.ts
Labels: sequencing

#1340 Fix plan name from being reset while editing if other plans are updated at the same time
  e2e-tests/fixtures/Plan.ts
  e2e-tests/tests/plan-activities.test.ts
  src/components/plan/PlanForm.svelte
Labels: fix

#1341 Release v2.11.1
  package-lock.json
  package.json
Labels: release

#1353 Decouples scan / publish for UI Docker image
  .github/workflows/publish.yml
Labels: ci

#1354 Release v2.14.0
  package-lock.json
  package.json
Labels: release
