Repository NASA-AMMOS/aerie-ui, pull requests merged in 2024-04, with the labels that each got.

#1203 Release v2.7.0
  package-lock.json
  package.json
Labels: release

#1204 Fix incorrect tag deletion logic
  e2e-tests/fixtures/Tags.ts
  e2e-tests/tests/tags.test.ts
  src/routes/tags/+page.svelte
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
Labels: fix

#1216 Release v2.6.99
  package-lock.json
  package.json
Labels: release

#1217 Release v2.6.100
  package-lock.json
  package.json
Labels: release

#1218 Release v2.6.101
  package-lock.json
  package.json
Labels: release

#1222 Add script for running playwright UI
  .vscode/tasks.json
  docs/TESTING.md
  package.json
Labels: refactor

#1224 Release v2.6.2
  package-lock.json
  package.json
Labels: release

#1229 Release v2.7.1
  package-lock.json
  package.json
Labels: release

#1181 Remove Insert Plan Scheduling Spec on Plan Creation
  .github/workflows/test.yml
  docker-compose-test.yml
  e2e-tests/fixtures/Plan.ts
  src/routes/plans/[id]/+page.ts
  src/utilities/effects.ts
Labels: refactor

#1231 Release v2.8.0
  package-lock.json
  package.json
Labels: release

#1227 Split `Test` workflow into `Unit` and `E2E` Jobs
  .github/workflows/test.yml
Labels: ci, refactor

#1233 Update log severity for Debug Statements in `hooks.server.ts`
  src/hooks.server.ts
Labels: refactor

#1225 ActivityDecomposition Pagination
  src/components/activity/ActivityDecomposition.svelte
  src/components/activity/ActivityDecomposition.svelte.test.ts
Labels: feature

#1249 Release v2.6.102
  package-lock.json
  package.json
Labels: release

#1253 Release v2.6.103
  package-lock.json
  package.json
Labels: release

#1254 Release v2.6.104
  package-lock.json
  package.json
Labels: release

#1257 Release v2.9.0
  package-lock.json
  package.json
Labels: release
