Repository NASA-AMMOS/aerie-ui, pull requests merged in 2025-08, with the labels that each got.

#1740 Release v3.6.0
  package-lock.json
  package.json
Labels: release

#1749 Improve error toast when user attempts to create anchor cycle
  src/utilities/effects.ts
  src/utilities/requests.ts
Labels: fix

#1739 Properly sort simulated activity table start offset column
  src/components/activity/ActivitySpansTablePanel.svelte
Labels: fix

#1732 Display plan import error in plan form
  src/components/Collapse.svelte
  src/routes/plans/+page.svelte
  src/utilities/effects.ts
Labels: fix

#1761 Fix: Model extraction status text mismatch
  src/components/model/ModelStatusRollup.svelte
Labels: error-message
