Repository NASA-AMMOS/aerie-ui, pull requests merged in 2025-04, with the labels that each got.

#1537 Procedural Constraints UI
  src/components/constraints/ConstraintForm.svelte
  src/components/constraints/ConstraintListItem.svelte
  src/components/constraints/ConstraintsPanel.svelte
  src/components/menus/Menu.svelte
  src/components/modals/ManagePlanConstraintsModal.svelte
  src/components/model/ModelAssociations.svelte
  src/components/model/ModelAssociationsListItem.svelte
  src/components/model/ModelSpecification.svelte
  src/components/parameters/ParameterBaseBoolean.svelte
  src/components/scheduling/SchedulingConditionsPanel.svelte
  src/components/scheduling/SchedulingGoalsPanel.svelte
  src/components/scheduling/conditions/SchedulingCondition.svelte
  src/components/scheduling/goals/SchedulingGoal.svelte
  src/components/scheduling/goals/SchedulingGoalForm.svelte
  src/components/ui/Association/AssociationForm.svelte
  src/enums/constraint.ts
  src/enums/gql.ts
  src/enums/scheduling.ts
  src/hooks.server.ts
  src/routes/constraints/edit/[id]/+page.svelte
  src/routes/models/[id]/+page.svelte
  src/routes/plans/[id]/+page.svelte
  src/routes/tags/+page.svelte
  src/stores/constraints.ts
  src/stores/scheduling.ts
  src/types/constraint.ts
  src/types/metadata.ts
  src/types/model.ts
  src/types/plan.ts
  src/types/scheduling.ts
  src/utilities/effects.test.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/parameters.test.ts
  src/utilities/parameters.ts
  src/utilities/permissionHandler.ts
  src/utilities/permissions.ts
Labels: constraints

#1671 Release v3.4.0
  package-lock.json
  package.json
Labels: release

#1645 Add readonly checkbox to sequences
  src/components/sequencing/SequenceEditor.svelte
  src/components/sequencing/SequenceForm.svelte
  src/components/sequencing/SequenceTable.svelte
  src/components/sequencing/Sequences.svelte
  src/components/ui/DataGrid/SingleActionDataGrid.svelte
  src/routes/sequencing/edit/[id]/+page.svelte
  src/stores/sequencing.ts
  src/types/sequencing.ts
  src/utilities/gql.ts
Labels: feature
