Repository NASA-AMMOS/aerie-ui, pull requests merged in 2025-09, with the labels that each got.

#1763 Add ability to convert imported files into target language
  src/components/modals/ImportWorkspaceFileModal.svelte
  src/components/modals/NewWorkspaceFolderModal.svelte
  src/components/modals/NewWorkspaceSequenceModal.svelte
  src/components/workspace/WorkspacesGrid.svelte
  src/routes/workspaces/[workspaceId]/+page.svelte
  src/utilities/effects.ts
  src/utilities/modal.ts
Labels: fix

#1779 Release v3.7.0
  package-lock.json
  package.json
Labels: release

#1777 Refactor recent activity modals to be more consistent with existing modals
  src/components/activity/ActivityDirectivesTable.svelte
  src/components/activity/ActivityDirectivesTablePanel.svelte
  src/components/modals/BulkShiftActivitiesModal.svelte
  src/components/modals/PackActivitiesOffsetModal.svelte
  src/utilities/activities.ts
  src/utilities/effects.ts
  src/utilities/modal.ts
Labels: refactor
