Repository NASA-AMMOS/aerie-ui, pull requests merged in 2025-02, with the labels that each got.

#1611 Addresses a11y labels error issue #1609
  src/components/TimelineItemList.svelte
  src/components/activity/ActivityDirectivesTablePanel.svelte
Labels: a11y

#1605 Use bulk default activity arguments and remove getEffectiveActivityArguments calls
  src/components/activity/ActivityDirectiveChangelog.svelte
  src/components/activity/ActivityDirectiveForm.svelte
  src/components/activity/ActivityFormPanel.svelte
  src/components/activity/ActivitySpanForm.svelte
  src/components/menus/PlanMenu.svelte
  src/components/plan/PlanForm.svelte
  src/components/ui/DataGrid/DataGridActions.svelte
  src/routes/plans/+page.svelte
  src/routes/plans/[id]/+page.ts
  src/utilities/effects.ts
  src/utilities/gql.ts
  src/utilities/permissions.ts
  src/utilities/plan.test.ts
  src/utilities/plan.ts
Labels: performance, refactor

#1630 Release v3.3.0
  package-lock.json
  package.json
Labels: release
